helics: helics::TcpCore Class Reference
helics::TcpCore Class Reference final
#include <TcpCore.h>
Public Member Functions
TcpCore () noexcept
TcpCore (const std::string &core_name)
virtual void initializeFromArgs (int argc, const char *const *argv) override
virtual std::string getAddress () const override
Public Member Functions inherited from helics::CommsBroker< TcpComms, CommonCore >
CommsBroker () noexcept
CommsBroker (bool arg) noexcept
CommsBroker (const std::string &obj_name)
~CommsBroker ()
virtual void transmit (int route_id, const ActionMessage &cmd) override
virtual void addRoute (int route_id, const std::string &routeInfo) override
Public Member Functions inherited from helics::CommonCore
CommonCore () noexcept
CommonCore (bool arg) noexcept
CommonCore (const std::string &core_name)
virtual ~CommonCore ()
virtual void initialize (const std::string &initializationString) override final
virtual bool isInitialized () const override final
virtual bool isOpenToNewFederates () const override final
virtual void error (federate_id_t federateID, int errorCode=-1) override final
virtual void finalize (federate_id_t federateID) override final
virtual void enterInitializingState (federate_id_t federateID) override final
virtual iteration_result enterExecutingState (federate_id_t federateID, helics_iteration_request iterate=NO_ITERATION) override final
virtual federate_id_t registerFederate (const std::string &name, const CoreFederateInfo &info) override final
virtual const std::string & getFederateName (federate_id_t federateID) const override final
virtual federate_id_t getFederateId (const std::string &name) override final
virtual int32_t getFederationSize () override final
virtual Time timeRequest (federate_id_t federateID, Time next) override final
virtual iteration_time requestTimeIterative (federate_id_t federateID, Time next, helics_iteration_request iterate) override final
virtual Time getCurrentTime (federate_id_t federateID) const override final
virtual uint64_t getCurrentReiteration (federate_id_t federateID) const override final
virtual void setMaximumIterations (federate_id_t federateID, int32_t iterations) override final
virtual void setTimeDelta (federate_id_t federateID, Time time) override final
virtual void setOutputDelay (federate_id_t federateID, Time outputDelayTime) override final
virtual void setPeriod (federate_id_t federateID, Time timePeriod) override final
virtual void setTimeOffset (federate_id_t federateID, Time timeOffset) override final
virtual void setInputDelay (federate_id_t federateID, Time impactTime) override final
virtual void setLoggingLevel (federate_id_t federateID, int loggingLevel) override final
virtual void setFlag (federate_id_t federateID, int flag, bool flagValue=true) override final
virtual handle_id_t registerSubscription (federate_id_t federateID, const std::string &key, const std::string &type, const std::string &units, handle_check_mode check_mode) override final
virtual handle_id_t getSubscription (federate_id_t federateID, const std::string &key) const override final
virtual handle_id_t registerPublication (federate_id_t federateID, const std::string &key, const std::string &type, const std::string &units) override final
virtual handle_id_t getPublication (federate_id_t federateID, const std::string &key) const override final
virtual const std::string & getHandleName (handle_id_t handle) const override final
virtual const std::string & getTarget (handle_id_t handle) const override final
virtual const std::string & getUnits (handle_id_t handle) const override final
virtual const std::string & getType (handle_id_t handle) const override final
virtual const std::string & getOutputType (handle_id_t handle) const override final
virtual void setValue (handle_id_t handle, const char *data, uint64_t len) override final
virtual std::shared_ptr< const data_block > getValue (handle_id_t handle) override final
virtual const std::vector< handle_id_t > & getValueUpdates (federate_id_t federateID) override final
virtual handle_id_t registerEndpoint (federate_id_t federateID, const std::string &name, const std::string &type) override final
virtual handle_id_t getEndpoint (federate_id_t federateID, const std::string &name) const override final
virtual handle_id_t registerSourceFilter (const std::string &filterName, const std::string &source, const std::string &type_in, const std::string &type_out) override final
virtual handle_id_t registerDestinationFilter (const std::string &filterName, const std::string &dest, const std::string &type_in, const std::string &type_out) override final
virtual handle_id_t getSourceFilter (const std::string &name) const override final
virtual handle_id_t getDestinationFilter (const std::string &name) const override final
virtual void addDependency (federate_id_t federateID, const std::string &federateName) override final
virtual void registerFrequentCommunicationsPair (const std::string &source, const std::string &dest) override final
virtual void send (handle_id_t sourceHandle, const std::string &destination, const char *data, uint64_t length) override final
virtual void sendEvent (Time time, handle_id_t sourceHandle, const std::string &destination, const char *data, uint64_t length) override final
virtual void sendMessage (handle_id_t sourceHandle, std::unique_ptr< Message > message) override final
virtual uint64_t receiveCount (handle_id_t destination) override final
virtual std::unique_ptr< Message > receive (handle_id_t destination) override final
virtual std::unique_ptr< Message > receiveAny (federate_id_t federateID, handle_id_t &endpoint_id) override final
virtual uint64_t receiveCountAny (federate_id_t federateID) override final
virtual void logMessage (federate_id_t federateID, int logLevel, const std::string &messageToLog) override final
virtual void setFilterOperator (handle_id_t filter, std::shared_ptr< FilterOperator > callback) override final
void setIdentifier (const std::string &name)
const std::string & getIdentifier () const override final
const std::string & getFederateNameNoThrow (federate_id_t federateID) const noexcept
virtual void setLoggingCallback (federate_id_t federateID, std::function< void(int, const std::string &, const std::string &)> logFunction) override final
virtual std::string query (const std::string &target, const std::string &queryStr) override
virtual void setQueryCallback (federate_id_t federateID, std::function< std::string(const std::string &)> queryFunction) override
virtual bool connect () override final
virtual bool isConnected () const override final
virtual void disconnect () override final
void unregister ()
virtual void processDisconnect (bool skipUnregister=false) override final
Public Member Functions inherited from helics::Core
Core ()=default
virtual ~Core ()=default
virtual handle_id_t registerSubscription (federate_id_t federateID, const std::string &key, const std::string &(type), const std::string &units, handle_check_mode check_mode)=0
Public Member Functions inherited from helics::BrokerBase
BrokerBase (const std::string &broker_name)
virtual void initializeFromCmdArgs (int argc, const char *const *argv)
void addActionMessage (const ActionMessage &m)
void addActionMessage (ActionMessage &&m)
void setLoggerFunction (std::function< void(int, const std::string &, const std::string &)> logFunction)
bool isRunning () const
void setLogLevel (int32_t level)
void setLogLevels (int32_t consoleLevel, int32_t fileLevel)
void joinAllThreads ()
Additional Inherited Members
Public Types inherited from helics::Core
using federate_id_t = int32_t
using handle_id_t = int32_t
Static Public Member Functions inherited from helics::BrokerBase
static void displayHelp ()
Protected Types inherited from helics::CommonCore
using fed_handle_pair = std::pair< federate_id_t, handle_id_t >
Protected Types inherited from helics::BrokerBase
enum broker_state_t : int {
created = -5, initialized = -4, connecting = -3, connected = -2,
initializing = -1, operating = 0, terminating = 1, terminated = 3,
errored = 7
}
Protected Member Functions inherited from helics::CommonCore
virtual void processCommand (ActionMessage &&cmd) override final
virtual void processPriorityCommand (ActionMessage &&command) override final
FederateState * getFederate (federate_id_t federateID) const
FederateState * getFederate (const std::string &federateName) const
FederateState * getHandleFederate (handle_id_t id_)
Core::handle_id_t getNewHandle ()
BasicHandleInfo * getHandleInfo (handle_id_t id_) const
BasicHandleInfo * getLocalEndpoint (const std::string &name)
FilterCoordinator * getFilterCoordinator (handle_id_t id_)
bool allInitReady () const
bool allDisconnected () const
virtual bool sendToLogger (federate_id_t federateID, int logLevel, const std::string &name, const std::string &message) const override
void deliverMessage (ActionMessage &message)
ActionMessage & processMessage (BasicHandleInfo *hndl, ActionMessage &m)
BasicHandleInfo * createBasicHandle (handle_id_t id_, federate_id_t global_federateId, federate_id_t local_federateId, BasicHandleType HandleType, const std::string &key, const std::string &type, const std::string &units, bool required)
BasicHandleInfo * createBasicHandle (handle_id_t id_, federate_id_t global_federateId, federate_id_t local_federateId, BasicHandleType HandleType, const std::string &key, const std::string &target, const std::string &type_in, const std::string &type_out)
bool isLocal (Core::federate_id_t global_id) const
int32_t getRoute (Core::federate_id_t global_id) const
void processFilterInfo (ActionMessage &command)
void organizeFilterOperations ()
std::string federateQuery (Core::federate_id_t federateID, const std::string &queryStr) const
void sendErrorToFederates (int error_code)
void distributeTimingMessage (ActionMessage &command)
Protected Member Functions inherited from helics::BrokerBase
void generateNewIdentifier ()
Protected Attributes inherited from helics::CommsBroker< TcpComms, CommonCore >
std::atomic< int > disconnectionStage
the stage of disconnection
std::mutex dataMutex
mutex protecting comms data
std::unique_ptr< TcpComms > comms
the actual comms object
std::atomic< bool > initialized_
atomic protecting local initialization
Protected Attributes inherited from helics::CommonCore
int32_t _global_federation_size = 0
total size of the federation
bool hasLocalFilters = false
std::atomic< int16_t > delayInitCounter
counter for the number of times the entry to initialization Mode was explicitly delayed
std::vector< std::unique_ptr< FederateState > > _federates
local federate information
std::atomic< int32_t > messageCounter { 54 }
counter for the number of messages that have been sent
std::vector< std::unique_ptr< BasicHandleInfo > > handles
local handle information
std::atomic< Core::handle_id_t > handleCounter {1}
counter for the handle index
std::unordered_map< std::string, handle_id_t > publications
map of all local publications
std::unordered_map< std::string, handle_id_t > endpoints
map of all local endpoints
std::unordered_map< std::string, federate_id_t > federateNames
map of federate names to id
std::vector< std::set< int32_t > > ongoingFilterProcesses
sets of ongoing filtered messages
std::vector< std::vector< ActionMessage > > delayedTimingMessages
delayedTimingMessages from ongoing Filter actions
std::atomic< int > queryCounter {0}
std::map< handle_id_t, std::unique_ptr< FilterCoordinator > > filterCoord
map of all local filters
DualMappedPointerVector< FilterInfo, std::string, fed_handle_pair > filters
storage for all the filters
Protected Attributes inherited from helics::BrokerBase
std::atomic< Core::federate_id_t > global_broker_id {0}
Core::federate_id_t higher_broker_id = 0
the id code of the broker 1 level about this broker
std::atomic< int32_t > maxLogLevel {1}
the logging level to use levels >=this will be logged
int32_t consoleLogLevel = 1
the logging level for console display
int32_t fileLogLevel = 1
the logging level for logging to a file
int32_t minFederateCount = 1
the minimum number of federates that must connect before entering init mode
int32_t minBrokerCount = 0
the minimum number of brokers that must connect before entering init mode
int32_t maxIterationCount = 10000
the maximum number of iterative loops that are allowed
int32_t tickTimer = 4000
counter for the length of a keep alive tick in milliseconds
int32_t timeout
timeout to wait to establish a broker connection before giving up in milliseconds
std::string identifier
an identifier for the broker
std::unique_ptr< Logger > loggingObj
default logging object to use if the logging callback is not specified
std::thread _queue_processing_thread
thread for running the broker
std::function< void(int, const std::string &, const std::string &)> loggerFunction
std::atomic< bool > haltOperations {false}
flag indicating that no further message should be processed
std::string logFile
std::unique_ptr< TimeCoordinator > timeCoord
object managing the time control
BlockingPriorityQueue< ActionMessage > actionQueue
primary routing queue
std::atomic< broker_state_t > brokerState {created}
bool noAutomaticID = false
bool hasTimeDependency = false
set to true if the broker has Time dependencies
bool enteredExecutionMode = false
flag indicating that the broker has entered execution mode
bool waitingForServerPingReply = false
flag indicating we are waiting for a ping reply
Detailed Description
implementation for the core that uses tcp messages to communicate
Constructor & Destructor Documentation
TcpCore()
helics::TcpCore::TcpCore () noexcept
default constructor
Member Function Documentation
getAddress()
std::string helics::TcpCore::getAddress () const override virtual
get a string representing the connection info to send data to this object
Implements helics::CommonCore.
References helics::CommsBroker< TcpComms, CommonCore >::comms, helics::CommsBroker< TcpComms, CommonCore >::dataMutex, helics::NetworkBrokerData::localInterface, helics::makePortAddress(), and helics::NetworkBrokerData::portNumber.
initializeFromArgs()
void helics::TcpCore::initializeFromArgs (int argc, const char *const * argv) override virtual
initialize the core manager with command line arguments
Parameters
[in] argc the number of arguments
[in] argv char pointers to the arguments
Reimplemented from helics::CommonCore.
References helics::BrokerBase::brokerState, helics::BrokerBase::created, helics::NetworkBrokerData::initializeFromArgs(), and helics::CommonCore::initializeFromArgs().
The documentation for this class was generated from the following files:
TcpCore.h
TcpCore.cpp