helics: helics::Source Class Reference
helics::Source Class Reference
#include <source.h>
Public Member Functions
Source ()=default
Source (int argc, char *argv[])
Source (const FederateInfo &fi)
Source (std::shared_ptr< Core > core, const FederateInfo &fi)
Source (const std::string &jsonString)
Source (Source &&other_source)=default
Source (const Source &other_source)=delete
Source & operator= (Source &&fed)=default
Source & operator= (const Source &fed)=delete
void loadFile (const std::string &filename)
void initialize ()
void run ()
void run (Time stopTime_input)
void addSource (const std::string &key, helics_type_t type, const std::string &units="")
Detailed Description
class implementing a source federate, which is capable of generating signals of various kinds and sending signals at the appropriate times
the source class is not threadsafe, don't try to use it from multiple threads without external protection, that will result in undefined behavior
Constructor & Destructor Documentation
Source() [1/7]
helics::Source::Source () default
default constructor
Source() [2/7]
helics::Source::Source (int argc, char * argv[])
construct from command line arguments
Parameters
argc the number of arguments
argv the strings in the input
References helics::argumentParser(), helics::FederateInfo::loadInfoFromArgs(), and helics::versionString().
Source() [3/7]
helics::Source::Source (const FederateInfo & fi)
construct from a federate info object
Parameters
fi a pointer info object containing information on the desired federate configuration
Source() [4/7]
helics::Source::Source (std::shared_ptr< Core > core, const FederateInfo & fi)
constructor taking a federate information structure and using the given core
Parameters
core a pointer to core object which the federate can join
[in] fi a federate information structure
Source() [5/7]
helics::Source::Source (const std::string & jsonString)
constructor taking a file with the required information
Parameters
[in] jsonString file or JSON string defining the federate information and other configuration
Source() [6/7]
helics::Source::Source (Source && other_source) default
move construction
Source() [7/7]
helics::Source::Source (const Source & other_source) delete
don't allow the copy constructor
Member Function Documentation
addSource()
void helics::Source::addSource (const std::string & key, helics_type_t type, const std::string & units = "")
add a publication to a source
Parameters
key the key of the publication to add
type the type of the publication
units the units associated with the publication
initialize()
void helics::Source::initialize ()
initialize the source federate
generate all the publications and organize the points, the final publication count will be available after this time and the source will enter the initialization mode, which means it will not be possible to add more publications calling run will automatically do this if necessary
Referenced by run().
loadFile()
void helics::Source::loadFile (const std::string & filename)
load a file containing publication information
Parameters
filename the file containing the configuration and source data accepted format are json, xml, and a source format which is tab delimited or comma delimited
References loadJsonString().
operator=() [1/2]
Source& helics::Source::operator= (Source && fed) default
move assignment
operator=() [2/2]
Source& helics::Source::operator= (const Source & fed) delete
don't allow the copy assignment, the default would fail anyway since federates are not copyable either
run()
void helics::Source::run (Time stopTime_input)
run the source until the specified time
Parameters
stopTime_input the desired stop time
References helics::Federate::execution, initialize(), TimeRepresentation< count_time< 9 > >::maxVal(), and helics::Federate::startup.
The documentation for this class was generated from the following files:
source.h
source.cpp