helics: helics::TestBroker Class Reference
helics::TestBroker Class Reference
#include <TestBroker.h>
Public Member Functions
TestBroker (bool isRoot_=false) noexcept
TestBroker (const std::string &broker_name)
TestBroker (std::shared_ptr< TestBroker > nbroker)
virtual void initializeFromArgs (int argc, const char *const *argv) override
virtual std::string getAddress () const override
Public Member Functions inherited from helics::CoreBroker
virtual bool connect () override final
virtual void disconnect () override final
void unregister ()
virtual void processDisconnect (bool skipUnregister=false) override final
virtual bool isConnected () const override final
virtual void setAsRoot () override final
virtual bool isRoot () const override final
virtual bool isOpenToNewFederates () const override
CoreBroker (bool setAsRootBroker=false) noexcept
CoreBroker (const std::string &broker_name)
virtual ~CoreBroker ()
virtual void initialize (const std::string &initializationString) override final
bool allInitReady () const
bool allDisconnected () const
void setIdentifier (const std::string &name)
virtual const std::string & getIdentifier () const override final
Public Member Functions inherited from helics::Broker
Broker ()=default
virtual ~Broker ()=default
Broker (std::string type, std::string name, std::string initString)
Broker (std::string type, std::string name, int argc, const char **argv)
bool isConnected ()
Public Member Functions inherited from helics::BrokerBase
BrokerBase (const std::string &broker_name)
virtual void initializeFromCmdArgs (int argc, const char *const *argv)
void addActionMessage (const ActionMessage &m)
void addActionMessage (ActionMessage &&m)
void setLoggerFunction (std::function< void(int, const std::string &, const std::string &)> logFunction)
bool isRunning () const
void setLogLevel (int32_t level)
void setLogLevels (int32_t consoleLevel, int32_t fileLevel)
void joinAllThreads ()
Static Public Member Functions
static void displayHelp (bool localOnly=false)
Static Public Member Functions inherited from helics::CoreBroker
static void displayHelp ()
Static Public Member Functions inherited from helics::BrokerBase
static void displayHelp ()
Protected Member Functions
virtual void transmit (int32_t route, const ActionMessage &command) override
virtual void addRoute (int route_id, const std::string &routeInfo) override
virtual bool brokerConnect () override
virtual void brokerDisconnect () override
virtual bool tryReconnect () override
Protected Member Functions inherited from helics::BrokerBase
virtual bool sendToLogger (Core::federate_id_t federateID, int logLevel, const std::string &name, const std::string &message) const
void generateNewIdentifier ()
Additional Inherited Members
Protected Types inherited from helics::BrokerBase
enum broker_state_t : int {
created = -5, initialized = -4, connecting = -3, connected = -2,
initializing = -1, operating = 0, terminating = 1, terminated = 3,
errored = 7
}
Protected Attributes inherited from helics::CoreBroker
bool _gateway = false
set to true if this broker should act as a gateway.
Protected Attributes inherited from helics::Broker
helics_broker broker
Protected Attributes inherited from helics::BrokerBase
std::atomic< Core::federate_id_t > global_broker_id {0}
Core::federate_id_t higher_broker_id = 0
the id code of the broker 1 level about this broker
std::atomic< int32_t > maxLogLevel {1}
the logging level to use levels >=this will be logged
int32_t consoleLogLevel = 1
the logging level for console display
int32_t fileLogLevel = 1
the logging level for logging to a file
int32_t minFederateCount = 1
the minimum number of federates that must connect before entering init mode
int32_t minBrokerCount = 0
the minimum number of brokers that must connect before entering init mode
int32_t maxIterationCount = 10000
the maximum number of iterative loops that are allowed
int32_t tickTimer = 4000
counter for the length of a keep alive tick in milliseconds
int32_t timeout
timeout to wait to establish a broker connection before giving up in milliseconds
std::string identifier
an identifier for the broker
std::unique_ptr< Logger > loggingObj
default logging object to use if the logging callback is not specified
std::thread _queue_processing_thread
thread for running the broker
std::function< void(int, const std::string &, const std::string &)> loggerFunction
std::atomic< bool > haltOperations {false}
flag indicating that no further message should be processed
std::string logFile
std::unique_ptr< TimeCoordinator > timeCoord
object managing the time control
BlockingPriorityQueue< ActionMessage > actionQueue
primary routing queue
std::atomic< broker_state_t > brokerState {created}
bool noAutomaticID = false
bool hasTimeDependency = false
set to true if the broker has Time dependencies
bool enteredExecutionMode = false
flag indicating that the broker has entered execution mode
bool waitingForServerPingReply = false
flag indicating we are waiting for a ping reply
Detailed Description
class implementing a basic broker that links to other brokers in process memory
Constructor & Destructor Documentation
TestBroker() [1/2]
helics::TestBroker::TestBroker (bool isRoot_ = false) noexcept
default constructor
TestBroker() [2/2]
helics::TestBroker::TestBroker (std::shared_ptr< TestBroker > nbroker)
construct with a pointer to a broker
Member Function Documentation
addRoute()
void helics::TestBroker::addRoute (int route_id, const std::string & routeInfo) override protected virtual
add a route to the type specific routing information and establish the connection
add a route to a table, the connection information is contained in the string with the described identifier
Parameters
[in] route_id the identifier for the route
[in] routeInfo a string describing the connection info
Implements helics::CoreBroker.
References helics::BrokerFactory::findBroker(), and helics::CoreFactory::findCore().
brokerConnect()
bool helics::TestBroker::brokerConnect () override protected virtual
implementation details of the connection process
Implements helics::CoreBroker.
References helics::BrokerFactory::cleanUpBrokers(), helics::BrokerFactory::create(), helics::BrokerFactory::findBroker(), and helics::TEST.
brokerDisconnect()
void helics::TestBroker::brokerDisconnect () override protected virtual
implementation details of the disconnection process
Implements helics::CoreBroker.
displayHelp()
void helics::TestBroker::displayHelp (bool localOnly = false) static
static method to display the help message
References helics::argumentParser(), and helics::CoreBroker::displayHelp().
getAddress()
std::string helics::TestBroker::getAddress () const override virtual
get the connection address for the broker
Implements helics::Broker.
initializeFromArgs()
void helics::TestBroker::initializeFromArgs (int argc, const char *const * argv) override virtual
initialize from command line arguments
Reimplemented from helics::CoreBroker.
References helics::argumentParser(), and helics::CoreBroker::initializeFromArgs().
transmit()
void helics::TestBroker::transmit (int32_t route, const ActionMessage & command) override protected virtual
this function is the one that will change for various flavors of broker communication
it takes a route info- a code of where to send the data and an action message and proceeds to transmit it to the appropriate location
Parameters
[in] route -the identifier for the routing information
[in] command the actionMessage to transmit
Implements helics::CoreBroker.
tryReconnect()
bool helics::TestBroker::tryReconnect () override protected virtual
in the case of connection failure with a broker this function will try a reconnect procedure
Implements helics::BrokerBase.
References helics::BrokerFactory::findBroker().
The documentation for this class was generated from the following files:
TestBroker.h
TestBroker.cpp