helics: helics::Player Class Reference
helics::Player Class Reference
#include <player.h>
Public Member Functions
Player ()=default
Player (int argc, char *argv[])
Player (const FederateInfo &fi)
Player (std::shared_ptr< Core > core, const FederateInfo &fi)
Player (const std::string &jsonString)
Player (Player &&other_player)=default
Player (const Player &other_player)=delete
Player & operator= (Player &&fed)=default
Player & operator= (const Player &fed)=delete
void loadFile (const std::string &filename)
void initialize ()
void run ()
void run (Time stopTime_input)
void addPublication (const std::string &key, helics_type_t type, const std::string &pubUnits=std::string())
template<class valType >
std::enable_if_t< helicsType< valType >) !=helics_type_t::helicsInvalid > addPublication (const std::string &key, const std::string &pubUnits=std::string())
void addEndpoint (const std::string &endpointName, const std::string &endpointType=std::string())
template<class valType >
void addPoint (Time pubTime, const std::string &key, const valType &val)
void addMessage (Time sendTime, const std::string &src, const std::string &dest, const std::string &payload)
void addMessage (Time sendTime, Time actionTime, const std::string &src, const std::string &dest, const std::string &payload)
auto pointCount () const
auto messageCount () const
auto publicationCount () const
auto endpointCount () const
void finalize ()
bool isActive () const
Detailed Description
class implementing a Player object, which is capable of reading a file and generating interfaces and sending signals at the appropriate times
the Player class is not thread-safe, don't try to use it from multiple threads without external protection, that will result in undefined behavior
Constructor & Destructor Documentation
Player() [1/7]
helics::Player::Player () default
default constructor
Player() [2/7]
helics::Player::Player (int argc, char * argv[])
construct from command line arguments
Parameters
argc the number of arguments
argv the strings in the input
References helics::argumentParser(), helics::FederateInfo::loadInfoFromArgs(), and helics::versionString().
Player() [3/7]
helics::Player::Player (const FederateInfo & fi) explicit
construct from a federate info object
Parameters
fi a pointer info object containing information on the desired federate configuration
Player() [4/7]
helics::Player::Player (std::shared_ptr< Core > core, const FederateInfo & fi)
constructor taking a federate information structure and using the given core
Parameters
core a pointer to core object which the federate can join
[in] fi a federate information structure
Player() [5/7]
helics::Player::Player (const std::string & jsonString) explicit
constructor taking a file with the required information
Parameters
[in] jsonString file or JSON string defining the federate information and other configuration
Player() [6/7]
helics::Player::Player (Player && other_player) default
move construction
Player() [7/7]
helics::Player::Player (const Player & other_player) delete
don't allow the copy constructor
Member Function Documentation
addEndpoint()
void helics::Player::addEndpoint (const std::string & endpointName, const std::string & endpointType = std::string())
add an endpoint to the Player
Parameters
endpointName the name of the endpoint
endpointType the named type of the endpoint
addMessage() [1/2]
void helics::Player::addMessage (Time sendTime, const std::string & src, const std::string & dest, const std::string & payload)
add a message to a Player queue
Parameters
pubTime the time the message should be sent
src the source endpoint of the message
dest the destination endpoint of the message
payload the payload of the message
addMessage() [2/2]
void helics::Player::addMessage (Time sendTime, Time actionTime, const std::string & src, const std::string & dest, const std::string & payload)
add an event for a specific time to a Player queue
Parameters
sendTime the time the message should be sent
actionTime the eventTime listed for the message
src the source endpoint of the message
dest the destination endpoint of the message
payload the payload of the message
addPoint()
template<class valType > void helics::Player::addPoint (Time pubTime, const std::string & key, const valType & val) inline
add a data point to publish through a Player
Parameters
pubTime the time of the publication
key the key for the publication
val the value to publish
addPublication() [1/2]
void helics::Player::addPublication (const std::string & key, helics_type_t type, const std::string & pubUnits = std::string())
add a publication to a Player
Parameters
key the key of the publication to add
type the type of the publication
units the units associated with the publication
addPublication() [2/2]
template<class valType > std::enable_if_t<helicsType<valType>) != helics_type_t::helicsInvalid> helics::Player::addPublication (const std::string & key, const std::string & pubUnits = std::string()) inline
add a publication to a Player
Parameters
key the key of the publication to add
type the type of the publication
units the units associated with the publication
endpointCount()
auto helics::Player::endpointCount () const inline
get the number of endpoints
finalize()
void helics::Player::finalize ()
finalize the Player federate
initialize()
void helics::Player::initialize ()
initialize the Player federate
generate all the publications and organize the points, the final publication count will be available after this time and the Player will enter the initialization mode, which means it will not be possible to add more publications calling run will automatically do this if necessary
References helics::Federate::startup.
Referenced by run().
isActive()
bool helics::Player::isActive () const inline
check if the Player is ready to run
loadFile()
void helics::Player::loadFile (const std::string & filename)
load a file containing publication information
Parameters
filename the file containing the configuration and Player data accepted format are JSON, xml, and a Player format which is tab delimited or comma delimited
messageCount()
auto helics::Player::messageCount () const inline
get the number of messages loaded
operator=() [1/2]
Player& helics::Player::operator= (Player && fed) default
move assignment
operator=() [2/2]
Player& helics::Player::operator= (const Player & fed) delete
don't allow the copy assignment, the default would fail anyway since federates are not copyable either
pointCount()
auto helics::Player::pointCount () const inline
get the number of points loaded
publicationCount()
auto helics::Player::publicationCount () const inline
get the number of publications
run()
void helics::Player::run (Time stopTime_input)
run the Player until the specified time
Parameters
stopTime_input the desired stop time
References TimeRepresentation< count_time< 9 > >::epsilon(), helics::Federate::execution, initialize(), TimeRepresentation< count_time< 9 > >::maxVal(), and helics::Federate::startup.
The documentation for this class was generated from the following files:
player.h
player.cpp