helics: helics::Publication Class Reference
helics::Publication Class Reference
Public Member Functions
Publication (ValueFederate *valueFed, const std::string &key, helics_type_t type, std::string units="")
Publication (interface_visibility locality, ValueFederate *valueFed, std::string key, helics_type_t type, const std::string &units=std::string())
Publication (ValueFederate *valueFed, int pubIndex)
void publish (double val) const
void publish (int64_t val) const
void publish (const char *val) const
void publish (const std::string &val) const
void publish (const std::vector< double > &val) const
void publish (const std::vector< std::complex< double >> &val) const
void publish (const double *vals, int size) const
void publish (std::complex< double > val) const
void publish (const defV &val) const
template<class X >
void publish (const X &val, const std::string &) const
void setMinimumChange (double deltaV)
void enableChangeDetection (bool enabled=true)
Public Member Functions inherited from helics::PublicationBase
PublicationBase (ValueFederate *valueFed, const std::string &key, const std::string &type, const std::string &units=std::string())
PublicationBase (interface_visibility locality, ValueFederate *valueFed, const std::string &key, const std::string &type, const std::string &units=std::string())
PublicationBase (ValueFederate *valueFed, int pubIndex)
virtual ~PublicationBase ()=default
publication_id_t getID () const
std::string getKey () const
const std::string & getName () const
const std::string & getType () const
const std::string & getUnits () const
Additional Inherited Members
Protected Attributes inherited from helics::PublicationBase
ValueFederate * fed = nullptr
the federate construct to interact with
publication_id_t id
the internal id of the publication
Constructor & Destructor Documentation
Publication() [1/3]
helics::Publication::Publication (ValueFederate * valueFed, const std::string & key, helics_type_t type, std::string units = "") inline
constructor to build a publication object
Parameters
[in] valueFed the ValueFederate to use
type_ the defined type of the publication
[in] name the name of the subscription
[in] units the units associated with a Federate
Publication() [2/3]
helics::Publication::Publication (interface_visibility locality, ValueFederate * valueFed, std::string key, helics_type_t type, const std::string & units = std::string()) inline
constructor to build a publication object
Parameters
locality set to global for a global publication or local for a local one
[in] valueFed the ValueFederate to use
type_ the defined type of the publication
[in] name the name of the subscription
[in] units the units associated with a Federate
Publication() [3/3]
helics::Publication::Publication (ValueFederate * valueFed, int pubIndex) inline
generate a publication object from a preexisting publication
Parameters
valueFed a pointer to the appropriate value Federate
pubIndex the index of the subscription
Member Function Documentation
publish() [1/2]
void helics::Publication::publish (double val) const
send a value for publication
Parameters
[in] val the value to publish
References helics::changeDetected(), helics::PublicationBase::fed, and helics::ValueFederate::publish().
Referenced by publish().
publish() [2/2]
template<class X > void helics::Publication::publish (const X & val, const std::string &) const inline
secondary publish function to allow unit conversion before publication
Parameters
[in] val the value to publish
[in] units the units association with the publication
References publish().
The documentation for this class was generated from the following files:
Publications.hpp
Publications.cpp