helics: helics::Recorder Class Reference
helics::Recorder Class Reference
#include <recorder.h>
Public Member Functions
Recorder (FederateInfo &fi)
Recorder (int argc, char *argv[])
Recorder (std::shared_ptr< Core > core, const FederateInfo &fi)
Recorder (const std::string &jsonString)
Recorder (Recorder &&other_player)=default
Recorder (const Recorder &other_player)=delete
Recorder & operator= (Recorder &&fed)=default
Recorder & operator= (const Recorder &fed)=delete
~Recorder ()
int loadFile (const std::string &filename)
void run ()
void run (Time stopTime)
void addSubscription (const std::string &key)
void addEndpoint (const std::string &endpoint)
void addSourceEndpointClone (const std::string &sourceEndpoint)
void addDestEndpointClone (const std::string &destEndpoint)
void addCapture (const std::string &captureDesc)
void saveFile (const std::string &filename)
auto pointCount () const
auto messageCount () const
std::pair< std::string, std::string > getValue (int index) const
std::unique_ptr< Message > getMessage (int index) const
void finalize ()
bool isActive () const
Protected Attributes
std::shared_ptr< CombinationFederate > fed
the federate
std::unique_ptr< CloningFilter > cFilt
a pointer to a clone filter
std::vector< ValueCapture > points
lists of points that were captured
std::vector< Subscription > subscriptions
the actual subscription objects
std::vector< Endpoint > endpoints
the actual endpoint objects
std::unique_ptr< Endpoint > cloneEndpoint
the endpoint for cloned message delivery
std::vector< std::unique_ptr< Message > > messages
list of messages
std::map< helics::subscription_id_t, int > subids
map of the subscription ids
std::map< std::string, int > subkeys
translate subscription names to an index
std::map< helics::endpoint_id_t, int > eptids
std::map< std::string, int > eptNames
translate endpoint name to index
std::vector< ValueStats > vStat
storage for statistics capture
std::vector< std::string > captureInterfaces
storage for the interfaces to capture
std::string mapfile
file name for the on-line file updater
std::string outFileName
the final output file
Time autoStopTime = Time::maxVal()
the stop time
bool deactivated = false
Detailed Description
class designed to capture data points from a set of subscriptions or endpoints
Constructor & Destructor Documentation
Recorder() [1/6]
helics::Recorder::Recorder (FederateInfo & fi)
construct from a FederateInfo structure
References fed.
Recorder() [2/6]
helics::Recorder::Recorder (int argc, char * argv[])
construct from command line arguments
References helics::argumentParser(), fed, helics::FederateInfo::loadInfoFromArgs(), and helics::versionString().
Recorder() [3/6]
helics::Recorder::Recorder (std::shared_ptr< Core > core, const FederateInfo & fi)
constructor taking a federate information structure and using the given core
Parameters
core a pointer to core object which the federate can join
[in] fi a federate information structure
References fed.
Recorder() [4/6]
helics::Recorder::Recorder (const std::string & jsonString)
constructor taking a file with the required information
Parameters
[in] file a file defining the federate information
References fed.
Recorder() [5/6]
helics::Recorder::Recorder (Recorder && other_player) default
move construction
Recorder() [6/6]
helics::Recorder::Recorder (const Recorder & other_player) delete
don't allow the copy constructor
~Recorder()
helics::Recorder::~Recorder ()
destructor
References outFileName, and saveFile().
Member Function Documentation
addCapture()
void helics::Recorder::addCapture (const std::string & captureDesc)
add a capture interface
Parameters
captureDesc describes a federate to capture all the interfaces for
References captureInterfaces.
addDestEndpointClone()
void helics::Recorder::addDestEndpointClone (const std::string & destEndpoint)
copy all messages that are going to a specific endpoint
References cFilt, cloneEndpoint, and fed.
addEndpoint()
void helics::Recorder::addEndpoint (const std::string & endpoint)
add an endpoint
addSourceEndpointClone()
void helics::Recorder::addSourceEndpointClone (const std::string & sourceEndpoint)
copy all messages that come from a specified endpoint
References cFilt, cloneEndpoint, and fed.
addSubscription()
void helics::Recorder::addSubscription (const std::string & key)
add a subscription to capture
add a subscription to record
References fed, subids, subkeys, and subscriptions.
finalize()
void helics::Recorder::finalize ()
finalize the federate
References fed.
getMessage()
std::unique_ptr< Message > helics::Recorder::getMessage (int index) const
get a message
makes a copy of a message and returns it in a unique_ptr
Parameters
index the number of the message to retrieve
References helics::isValidIndex(), and messages.
getValue()
std::pair< std::string, std::string > helics::Recorder::getValue (int index) const
get a string with the value of point index
Parameters
index the number of the point to retrieve
Returns
a pair with the tag as the first element and the value as the second
References helics::isValidIndex(), points, and subscriptions.
isActive()
bool helics::Recorder::isActive () const inline
check if the Recorder is ready to run
loadFile()
int helics::Recorder::loadFile (const std::string & filename)
load a file containing subscription information
Parameters
filename the name of the file to load (.txt, .json, or .xml
Returns
0 on success <0 on failure
messageCount()
auto helics::Recorder::messageCount () const inline
get the number of captured messages
References messages.
operator=() [1/2]
Recorder& helics::Recorder::operator= (Recorder && fed) default
move assignment
operator=() [2/2]
Recorder& helics::Recorder::operator= (const Recorder & fed) delete
don't allow the copy assignment, the default would fail anyway since federates are not copyable either
pointCount()
auto helics::Recorder::pointCount () const inline
get the number of captured points
References points.
run()
void helics::Recorder::run (Time runToTime)
run the Player until the specified time
References fed, mapfile, and vStat.
saveFile()
void helics::Recorder::saveFile (const std::string & filename)
save the data to a file
Referenced by ~Recorder().
The documentation for this class was generated from the following files:
recorder.h
recorder.cpp