helics: TcpConnection Class Reference
TcpConnection Class Reference
#include <TcpHelperClasses.h>
Public Types
typedef std::shared_ptr< TcpConnection > pointer
Public Member Functions
boost::asio::ip::tcp::socket & socket ()
void cancel ()
void close ()
void send (const void *buffer, size_t dataLength)
void send (const std::string &dataString)
size_t receive (void *buffer, size_t maxDataSize)
template<typename Process >
void send_async (const void *buffer, size_t dataLength, Process callback)
template<typename Process >
void async_receive (void *buffer, size_t dataLength, Process callback)
void async_receive (std::function< void(TcpConnection::pointer, const char *, size_t, const boost::system::error_code &error)> callback)
bool isConnected () const
int waitUntilConnected (int timeOut)
Static Public Member Functions
static pointer create (boost::asio::io_service &io_service, const std::string &connection, const std::string &port, size_t bufferSize=10192)
Detailed Description
tcp socket connection for connecting to a server
Member Function Documentation
async_receive() [1/2]
template<typename Process > void TcpConnection::async_receive (void * buffer, size_t dataLength, Process callback) inline
perform an asynchronous receive operation
Parameters
buffer the data to send
dataLength the length of the data
callback a callback function of the form void handler(const boost::system::error_code& error, // Result of operation. std::size_t bytes_transferred // Number of bytes received.);
async_receive() [2/2]
void TcpConnection::async_receive (std::function< void(TcpConnection::pointer, const char *, size_t, const boost::system::error_code &error)> callback) inline
perform an asynchronous receive operation
Parameters
buffer the data to send
dataLength the length of the data
callback a callback function of the form void handler(const boost::system::error_code& error, // Result of operation. std::size_t bytes_transferred // Number of bytes received.);
References error.
close()
void TcpConnection::close ()
close the socket connection
Parameters
isConnected()
bool TcpConnection::isConnected () const inline
check if the socket has finished the connection process
Referenced by send(), and waitUntilConnected().
receive()
size_t TcpConnection::receive (void * buffer, size_t maxDataSize)
do a blocking receive on the socket
Exceptions
boost::system::system_error on failure
Returns
the number of bytes received
send() [1/2]
void TcpConnection::send (const void * buffer, size_t dataLength)
send raw data
Exceptions
boost::system::system_error on failure
References isConnected(), and waitUntilConnected().
send() [2/2]
void TcpConnection::send (const std::string & dataString)
send a string
Exceptions
boost::system::system_error on failure
References isConnected(), and waitUntilConnected().
send_async()
template<typename Process > void TcpConnection::send_async (const void * buffer, size_t dataLength, Process callback) inline
perform an asynchronous send operation
Parameters
buffer the data to send
dataLength the length of the data
callback a callback function of the form void handler(const boost::system::error_code& error, // Result of operation. std::size_t bytes_transferred // Number of bytes received.);
waitUntilConnected()
int TcpConnection::waitUntilConnected (int timeOut)
wait until the socket has finished the connection process
Parameters
timeOut the number of ms to wait for the connection process to finish (-1) for no limit
Returns
0 if connected, -1 if the timeout was reached, -2 if error
References isConnected().
Referenced by send().
The documentation for this class was generated from the following files:
TcpHelperClasses.h
TcpHelperClasses.cpp