helics: helics::Echo Class Reference
helics::Echo Class Reference
#include <echo.h>
Public Member Functions
Echo ()=default
Echo (int argc, char *argv[])
Echo (const FederateInfo &fi)
Echo (std::shared_ptr< Core > core, const FederateInfo &fi)
Echo (const std::string &jsonString)
Echo (Echo &&other_echo)=default
Echo (const Echo &other_echo)=delete
Echo & operator= (Echo &&fed)=default
Echo & operator= (const Echo &fed)=delete
void loadFile (const std::string &filename)
void initialize ()
void run ()
void run (Time stopTime_input)
void addEndpoint (const std::string &endpointName, const std::string &endpointType="")
auto echoCount () const
auto endpointCount () const
bool isActive () const
Detailed Description
class implementing a Echo object, which will generate endpoint interfaces and send a data message back to the source at the with a specified delay
the Echo class is not threadsafe, don't try to use it from multiple threads without external protection, that will result in undefined behavior
Constructor & Destructor Documentation
Echo() [1/7]
helics::Echo::Echo () default
default constructor
Echo() [2/7]
helics::Echo::Echo (int argc, char * argv[])
construct from command line arguments
Parameters
argc the number of arguments
argv the strings in the input
References helics::argumentParser(), helics::FederateInfo::loadInfoFromArgs(), and helics::versionString().
Echo() [3/7]
helics::Echo::Echo (const FederateInfo & fi)
construct from a federate info object
Parameters
fi a pointer info object containing information on the desired federate configuration
Echo() [4/7]
helics::Echo::Echo (std::shared_ptr< Core > core, const FederateInfo & fi)
constructor taking a federate information structure and using the given core
Parameters
core a pointer to core object which the federate can join
[in] fi a federate information structure
Echo() [5/7]
helics::Echo::Echo (const std::string & jsonString)
constructor taking a file with the required information
Parameters
[in] jsonString file or json string defining the federate information and other configuration
References loadFile().
Echo() [6/7]
helics::Echo::Echo (Echo && other_echo) default
move construction
Echo() [7/7]
helics::Echo::Echo (const Echo & other_echo) delete
don't allow the copy constructor
Member Function Documentation
addEndpoint()
void helics::Echo::addEndpoint (const std::string & endpointName, const std::string & endpointType = "")
add an endpoint to the Player
Parameters
endpointName the name of the endpoint
endpointType the named type of the endpoint
echoCount()
auto helics::Echo::echoCount () const inline
get the number of points loaded
endpointCount()
auto helics::Echo::endpointCount () const inline
get the number of endpoints
initialize()
void helics::Echo::initialize ()
initialize the Player federate
generate all the publications and organize the points, the final publication count will be available after this time and the Player will enter the initialization mode, which means it will not be possible to add more publications calling run will automatically do this if necessary
References helics::Federate::startup.
Referenced by run().
isActive()
bool helics::Echo::isActive () const inline
check if the Player is ready to run
loadFile()
void helics::Echo::loadFile (const std::string & filename)
load a file containing publication information
Parameters
filename the file containing the configuration and Player data accepted format are json, xml, and a Player format which is tab delimited or comma delimited
Referenced by Echo().
operator=() [1/2]
Echo& helics::Echo::operator= (Echo && fed) default
move assignment
operator=() [2/2]
Echo& helics::Echo::operator= (const Echo & fed) delete
don't allow the copy assignment, the default would fail anyway since federates are not copyable either
run()
void helics::Echo::run (Time stopTime_input)
run the Echo federate until the specified time
Parameters
stopTime_input the desired stop time
References helics::Federate::execution, initialize(), TimeRepresentation< count_time< 9 > >::maxVal(), and helics::Federate::startup.
The documentation for this class was generated from the following files:
echo.h
echo.cpp