helics: helics Namespace Reference
helics Namespace Reference
Namespaces
BrokerFactory
CoreFactory
Classes
class _object
class ActionMessage
class ArgDescriptor
class AsyncFedCallInfo
class Barrier
class BasicBrokerInfo
class BasicFedInfo
class BasicHandleInfo
class BlockingQueue_old
class Broker
class BrokerBase
class BrokerObject
class changeOnDestroy
class CloneFilterOperation
class CloneOperator
class CloningFilter
class CombinationFederate
class CommonCore
class CommsBroker
class CommsInterface
class conditionalChangeOnDestroy
class ConnectionFailure
class Core
class CoreBroker
class CoreFederateInfo
class CoreObject
class data_block
class data_t
class data_view
class DelayFilterOperation
class DependencyInfo
class DestinationFilter
class Echo
class Endpoint
class endpoint_info
class EndpointInfo
class EndpointObject
class Federate
class FederateInfo
class FederateState
class FedObject
class Filter
class FilterCoordinator
class FilterInfo
class FilterObject
class FilterOperations
class FilterOperator
class FunctionExecutionFailure
class HandleManager
struct helics_iteration_time
class HelicsException
class HelicsTerminated
class identifier_id_t
class InvalidFunctionCall
class InvalidIdentifier
class InvalidParameter
class InvalidParameterValue
class InvalidStateTransition
class IpcBroker
class IpcComms
class IpcCore
struct is_iterable
struct is_iterable< T, typename std::enable_if_t< std::is_same< decltype(std::begin(T()) !=std::end(T()), void(), void(*std::begin(T())), std::true_type{}), std::true_type >::value > >
struct is_vector
struct is_vector< T, typename std::enable_if_t< std::is_same< T, std::vector< typename T::value_type, typename T::allocator_type > >::value > >
struct iteration_time
class Logger
class LoggerManager
class LoggerNoThread
class LoggingCore
class Message
class message_t
class MessageConditionalOperator
class MessageDataOperator
class MessageDestOperator
class MessageFederate
class MessageFederateManager
class MessageHolder
class MessageTimeOperator
class MpiBroker
class MpiComms
class MpiCore
class NetworkBrokerData
class NullFilterOperator
class ownedQueue
class Player
class Publication
struct publication_info
class PublicationBase
class PublicationInfo
class PublicationObject
class PublicationOnChange
class PublicationT
class queryObject
class RandomDelayFilterOperation
class RandomDropFilterOperation
class Recorder
class RegistrationFailure
class RerouteFilterOperation
class sendToQueue
class shared_queue_state
class Source
class SourceFilter
class SourceObject
class Subscription
struct subscription_info
class SubscriptionBase
class SubscriptionInfo
class SubscriptionObject
class SubscriptionT
class TcpBroker
class TcpComms
class TcpCore
class TestBroker
class TestCore
class TimeCoordinator
class TimeDependencies
class UdpBroker
class UdpComms
class UdpCore
class ValueCapture
class ValueConverter
class ValueConverter< std::string >
class ValueFederate
class ValueFederateManager
class ValueSetter
class ValueStats
class VectorSubscription
class VectorSubscription2d
class waitingResponse
class ZmqBroker
class ZmqComms
class ZmqCore
class ZmqRequestSets
Typedefs
using defV = boost::variant< double, int64_t, std::string, std::complex< double >, std::vector< double >, std::vector< std::complex< double > >>
using identifier_type = uint32_t
using publication_id_t = identifier_id_t< identifier_type, identifiers::publication, invalid_id_value >
using subscription_id_t = identifier_id_t< identifier_type, identifiers::subscription, invalid_id_value >
using endpoint_id_t = identifier_id_t< identifier_type, identifiers::endpoint, invalid_id_value >
using filter_id_t = identifier_id_t< identifier_type, identifiers::filter, invalid_id_value >
using query_id_t = identifier_id_t< identifier_type, identifiers::query, invalid_id_value >
using ArgDescriptors = std::vector< ArgDescriptor >
using variable_map = boost::program_options::variables_map
using archiver = cereal::PortableBinaryOutputArchive
using retriever = cereal::PortableBinaryInputArchive
using actionPair = std::pair< action_message_def::action_t, const char * >
using activeProtector = std::shared_ptr< libguarded::guarded< bool > >
using federate_id_t = Core::federate_id_t
using handle_id_t = Core::handle_id_t
using Time = TimeRepresentation< count_time< 9 > >
Enumerations
enum random_dists_t : int {
constant, uniform, bernoulli, binomial,
geometric, poisson, exponential, gamma,
weibull, extreme_value, normal, lognormal,
chi_squared, cauchy, fisher_f, student_t
}
enum defined_filter_types {
custom = 0, delay = 1, randomDelay = 2, randomDrop = 3,
reroute = 4, clone = 5, unrecognized = 6
}
enum type_location {
doubleLoc = 0, intLoc = 1, stringLoc = 2, complexLoc = 3,
vectorLoc = 4, complexVectorLoc = 5
}
enum identifiers : char {
publication, subscription, filter, endpoint,
query
}
enum interface_visibility { local, global }
enum helics_type_t : int {
helicsString = 0, helicsDouble = 1, helicsInt = 2, helicsComplex = 3,
helicsVector = 4, helicsComplexVector = 5, helicsInvalid = 23425, helicsAny = 247652
}
enum action_message_flags : uint16_t {
iterationRequested = 0, processingComplete = 1, pub_required = 2, filt_required = 3,
error_flag = 4, indicator_flag = 5, extra_flag1 = 7
}
enum BasicHandleType : char {
HANDLE_UNKNOWN, HANDLE_PUB, HANDLE_SUB, HANDLE_END,
HANDLE_SOURCE_FILTER, HANDLE_DEST_FILTER, HANDLE_CLONE_FILTER
}
enum core_type : int {
core_type::DEFAULT = 0, core_type::ZMQ = 1, core_type::MPI = 2, core_type::TEST = 3,
core_type::INTERPROCESS = 4, core_type::IPC = 5, core_type::TCP = 6, core_type::UDP = 7,
core_type::UNRECOGNIZED = 8
}
enum iteration_state : signed char {
iteration_state::error = -5, iteration_state::continue_processing = -1, iteration_state::next_step = 0, iteration_state::iterating = 2,
iteration_state::halted = 3
}
enum iteration_result : signed char { iteration_result::error = -5, iteration_result::next_step = 0, iteration_result::iterating = 2, iteration_result::halted = 3 }
enum helics_iteration_request : signed char { helics_iteration_request::no_iterations = 0, helics_iteration_request::force_iteration = 1, helics_iteration_request::iterate_if_needed = 2 }
enum handle_check_mode : char { handle_check_mode::required = 0, handle_check_mode::optional = 1 }
enum queue_state_t : int {
unknown = -1, startup = 0, connected = 1, operating = 2,
closing = 3
}
enum PubSubTypes {
STRING_TYPE = 0, DOUBLE_TYPE = 1, INT_TYPE = 2, COMPLEX_TYPE = 3,
VECTOR_TYPE = 4, RAW_TYPE = 25
}
enum vtype : int { genericFed, valueFed, messageFed, combinationFed }
enum ftype { source, dest, clone }
Functions
void cleanupHelicsLibrary ()
FederateInfo loadFederateInfo (const std::string &jsonString)
double randDouble (random_dists_t dist, double p1, double p2)
defined_filter_types filterTypeFromString (const std::string &filterType) noexcept
void addOperations (Filter *filt, defined_filter_types type, Core *cptr)
std::unique_ptr< DestinationFilter > make_destination_filter (defined_filter_types type, Federate *mFed, const std::string &target, const std::string &name)
std::unique_ptr< SourceFilter > make_source_filter (defined_filter_types type, Core *cr, const std::string &target, const std::string &name)
std::unique_ptr< DestinationFilter > make_destination_filter (defined_filter_types type, Core *cr, const std::string &target, const std::string &name)
std::unique_ptr< SourceFilter > make_source_filter (defined_filter_types type, Federate *fed, const std::string &target, const std::string &name)
bool changeDetected (const defV &prevValue, const std::string &val, double)
bool changeDetected (const defV &prevValue, const std::vector< double > &val, double deltaV)
bool changeDetected (const defV &prevValue, const std::vector< std::complex< double >> &val, double deltaV)
bool changeDetected (const defV &prevValue, const double *vals, size_t size, double deltaV)
bool changeDetected (const defV &prevValue, const std::complex< double > &val, double deltaV)
bool changeDetected (const defV &prevValue, double val, double deltaV)
bool changeDetected (const defV &prevValue, int64_t val, double deltaV)
void valueExtract (const defV &dv, std::string &val)
void valueExtract (const defV &dv, std::complex< double > &val)
void valueExtract (const defV &dv, std::vector< double > &val)
void valueExtract (const defV &dv, std::vector< std::complex< double >> &val)
void valueExtract (const data_view &dv, helics_type_t baseType, std::string &val)
void valueExtract (const data_view &dv, helics_type_t baseType, std::vector< double > &val)
void valueExtract (const data_view &dv, helics_type_t baseType, std::vector< std::complex< double >> &val)
void valueExtract (const data_view &dv, helics_type_t baseType, std::complex< double > &val)
template<class X >
std::enable_if_t< std::is_arithmetic< X >::value > valueExtract (const defV &dv, X &val)
template<class X >
std::enable_if_t< std::is_arithmetic< X >::value > valueExtract (const data_view &dv, helics_type_t baseType, X &val)
const std::string & typeNameStringRef (helics_type_t type)
std::string helicsComplexString (double real, double imag)
std::string helicsComplexString (std::complex< double > val)
helics_type_t getTypeFromString (const std::string &typeName)
const std::regex creg (R"(([+-]?(\(\+)?|\+)([eE][+-]?\)?)\([+-]\(\(\+)?|\+)([eE][+-]?\)?)[ji]*)")
std::complex< double > helicsGetComplex (const std::string &val)
std::string helicsVectorString (const std::vector< double > &val)
std::string helicsVectorString (const double *vals, size_t size)
std::string helicsComplexVectorString (const std::vector< std::complex< double >> &val)
std::vector< double > helicsGetVector (const std::string &val)
std::vector< std::complex< double > > helicsGetComplexVector (const std::string &val)
void helicsGetVector (const std::string &val, std::vector< double > &data)
void helicsGetComplexVector (const std::string &val, std::vector< std::complex< double >> &data)
data_block typeConvert (helics_type_t type, double val)
data_block typeConvert (helics_type_t type, int64_t val)
data_block typeConvert (helics_type_t type, const char *val)
data_block typeConvert (helics_type_t type, const std::string &val)
data_block typeConvert (helics_type_t type, const std::vector< double > &val)
data_block typeConvert (helics_type_t type, const double *vals, size_t size)
data_block typeConvert (helics_type_t type, const std::vector< std::complex< double >> &val)
data_block typeConvert (helics_type_t type, const std::complex< double > &val)
template<class X >
std::string typeNameString ()
template<>
std::string typeNameString< std::vector< std::string > > ()
template<>
std::string typeNameString< std::vector< double > > ()
template<>
std::string typeNameString< std::vector< std::complex< double > > > ()
template<>
std::string typeNameString< double > ()
template<>
std::string typeNameString< float > ()
template<>
std::string typeNameString< char > ()
template<>
std::string typeNameString< unsigned char > ()
template<>
std::string typeNameString< std::int32_t > ()
template<>
std::string typeNameString< std::uint32_t > ()
template<>
std::string typeNameString< int64_t > ()
template<>
std::string typeNameString< std::uint64_t > ()
template<>
std::string typeNameString< std::complex< float > > ()
template<>
std::string typeNameString< std::complex< double > > ()
template<>
std::string typeNameString< std::string > ()
template<class X >
constexpr helics_type_t helicsType ()
template<>
constexpr helics_type_t helicsType< int64_t > ()
template<>
constexpr helics_type_t helicsType< std::string > ()
template<>
constexpr helics_type_t helicsType< double > ()
template<>
constexpr helics_type_t helicsType< std::complex< double > > ()
template<>
constexpr helics_type_t helicsType< std::vector< double > > ()
template<>
constexpr helics_type_t helicsType< std::vector< std::complex< double > > > ()
template<class X >
constexpr bool isConvertableType ()
template<class X >
constexpr std::enable_if< helicsType< X >) !=helics_type_t::helicsInvalid, bool >::type isConvertableType ()
template<>
constexpr bool isConvertableType< float > ()
template<>
constexpr bool isConvertableType< long double > ()
template<>
constexpr bool isConvertableType< int > ()
template<>
constexpr bool isConvertableType< short > ()
template<>
constexpr bool isConvertableType< unsigned int > ()
template<>
constexpr bool isConvertableType< char > ()
template<>
constexpr bool isConvertableType< uint64_t > ()
template<class X >
X invalidValue ()
template<>
constexpr double invalidValue< double > ()
template<>
constexpr uint64_t invalidValue< uint64_t > ()
template<>
constexpr std::complex< double > invalidValue< std::complex< double > > ()
template<>
std::string typeNameString< std::vector< data_block > > ()
data_block typeConvert (helics_type_t type, const defV &val)
template<class X >
std::enable_if_t< helicsType< X >) !=helics_type_t::helicsInvalid, std::unique_ptr< Publication > > make_publication (ValueFederate *valueFed, const std::string &name, const std::string &units=std::string())
template<class X >
std::enable_if_t< helicsType< X >) !=helics_type_t::helicsInvalid, std::unique_ptr< Publication > > make_publication (interface_visibility locality, ValueFederate *valueFed, const std::string &name, const std::string &units=std::string())
template<class Archive >
void save (Archive &ar, const data_block &db)
template<class Archive >
void load (Archive &ar, data_block &db)
template<class Archive >
void save (Archive &ar, const data_view &db)
template<class Archive >
void load (Archive &ar, data_view &db)
template<class X >
constexpr std::enable_if_t<!is_iterable< X >::value &&!std::is_convertible< X, std::string >::value, size_t > getMinSize ()
template<class X >
constexpr std::enable_if_t< is_iterable< X >::value &&!std::is_convertible< X, std::string >::value, size_t > getMinSize ()
template<class X >
constexpr std::enable_if_t< std::is_convertible< X, std::string >::value, size_t > getMinSize ()
template<class... Us>
void publish (std::shared_ptr< ValueFederate > &fed, const std::string &pubKey, Us... pargs)
template<class... Us>
void publish (ValueFederate &fed, const std::string &pubKey, Us... pargs)
template<class X >
X getValue (std::shared_ptr< ValueFederate > &fed, const std::string &Key)
template<class X >
void getValue (std::shared_ptr< ValueFederate > &fed, const std::string &Key, X &obj)
template<class X >
X getValue (ValueFederate &fed, const std::string &Key)
template<class X >
void getValue (ValueFederate &fed, const std::string &Key, X &obj)
int getTypeSize (const std::string type)
bool isBlockSizeValid (int size, const publication_info &pubI)
int argumentParser (int argc, const char *const *argv, variable_map &vm_map, const ArgDescriptors &argDefinitions, const std::string &posName)
constexpr int helpReturn (-1)
constexpr int versionReturn (-2)
std::unique_ptr< Message > createMessageFromCommand (const ActionMessage &cmd)
std::unique_ptr< Message > createMessageFromCommand (ActionMessage &&cmd)
const char * actionMessageType (action_message_def::action_t action)
std::string prettyPrintString (const ActionMessage &command)
std::ostream & operator<< (std::ostream &os, const ActionMessage &command)
template<class FlagContainer , class FlagIndex >
void setActionFlag (FlagContainer &M, FlagIndex flag)
template<class FlagContainer , class FlagIndex >
bool checkActionFlag (const FlagContainer &M, FlagIndex flag)
template<class FlagContainer , class FlagIndex >
void clearActionFlag (FlagContainer &M, FlagIndex flag)
bool isProtocolCommand (const ActionMessage &command) noexcept
bool isPriorityCommand (const ActionMessage &command) noexcept
bool isTimingCommand (const ActionMessage &command) noexcept
bool isDependencyCommand (const ActionMessage &command) noexcept
bool isDisconnectCommand (const ActionMessage &command) noexcept
bool isValidCommand (const ActionMessage &command) noexcept
bool hasInfo (action_message_def::action_t action)
void timerTickHandler (BrokerBase *bbase, activeProtector active, const boost::system::error_code &error)
std::shared_ptr< Broker > makeBroker (core_type type, const std::string &name)
bool matchingTypes (const std::string &type1, const std::string &type2)
bool operator!= (const data_block &db1, const data_block &db2)
template<class sizeType , class SizedDataType >
bool isValidIndex (sizeType testSize, const SizedDataType &vec)
std::string helicsTypeString (core_type type)
core_type coreTypeFromString (std::string type)
bool isCoreTypeAvailable (core_type type) noexcept
uint64_t makeGlobalHandleIdentifier (Core::federate_id_t fed_id, Core::handle_id_t handle)
std::shared_ptr< Core > makeCore (core_type type, const std::string &name)
timeUnits timeUnitsFromString (const std::string &unitString)
helics::Time loadTimeFromString (const std::string &timeString)
helics::Time loadTimeFromString (const std::string &timeString, timeUnits defUnits)
constexpr Time operator"" _t (long double val)
std::string versionString ()
std::string stringTranslateToCppName (std::string in)
std::string makePortAddress (const std::string &networkInterface, int portNumber)
std::pair< std::string, int > extractInterfaceandPort (const std::string &address)
std::pair< std::string, std::string > extractInterfaceandPortString (const std::string &address)
std::string getLocalExternalAddressV4 ()
std::string getLocalExternalAddressV4 (const std::string &)
std::string getHelicsVersionString ()
def swig_import_helper ()
def helicsGetVersion ()
def helicsIsCoreTypeAvailable (type)
def helicsCreateCore (type, name, initString)
def helicsCreateCoreFromArgs (type, name, argc, argv)
def helicsCreateBroker (type, name, initString)
def helicsCreateBrokerFromArgs (type, name, argc, argv)
def helicsBrokerIsConnected (broker)
def helicsCoreIsConnected (core)
def helicsBrokerGetIdentifier (broker, identifier, maxlen)
def helicsCoreGetIdentifier (core, identifier, maxlen)
def helicsBrokerGetAddress (broker, address, maxlen)
def helicsCoreDisconnect (core)
def helicsBrokerDisconnect (broker)
def helicsCoreFree (core)
def helicsBrokerFree (broker)
def helicsCreateValueFederate (fi)
def helicsCreateValueFederateFromJson (json)
def helicsCreateMessageFederate (fi)
def helicsCreateMessageFederateFromJson (json)
def helicsCreateCombinationFederate (fi)
def helicsCreateCombinationFederateFromJson (json)
def helicsFederateInfoCreate ()
def helicsFederateInfoLoadFromArgs (fi, argc, argv)
def helicsFederateInfoFree (fi)
def helicsFederateInfoSetFederateName (fi, name)
def helicsFederateInfoSetCoreName (fi, corename)
def helicsFederateInfoSetCoreInitString (fi, coreInit)
def helicsFederateInfoSetCoreTypeFromString (fi, coretype)
def helicsFederateInfoSetCoreType (fi, coretype)
def helicsFederateInfoSetFlag (fi, flag, value)
def helicsFederateInfoSetOutputDelay (fi, outputDelay)
def helicsFederateInfoSetTimeDelta (fi, timeDelta)
def helicsFederateInfoSetInputDelay (fi, inputDelay)
def helicsFederateInfoSetTimeOffset (fi, timeOffset)
def helicsFederateInfoSetPeriod (fi, period)
def helicsFederateInfoSetMaxIterations (fi, maxIterations)
def helicsFederateInfoSetLoggingLevel (fi, logLevel)
def helicsFederateFinalize (fed)
def helicsFederateFree (fed)
def helicsCloseLibrary ()
def helicsFederateEnterInitializationMode (fed)
def helicsFederateEnterInitializationModeAsync (fed)
def helicsFederateIsAsyncOperationCompleted (fed)
def helicsFederateEnterInitializationModeComplete (fed)
def helicsFederateEnterExecutionMode (fed)
def helicsFederateEnterExecutionModeAsync (fed)
def helicsFederateEnterExecutionModeComplete (fed)
def helicsFederateEnterExecutionModeIterative (fed, iterate, outIterate)
def helicsFederateEnterExecutionModeIterativeAsync (fed, iterate)
def helicsFederateEnterExecutionModeIterativeComplete (fed, outIterate)
def helicsFederateGetState (fed, state)
def helicsFederateGetCoreObject (fed)
def helicsFederateRequestTime (fed, requestTime)
def helicsFederateRequestTimeIterative (fed, requestTime, iterate, outIterate)
def helicsFederateRequestTimeAsync (fed, requestTime)
def helicsFederateRequestTimeComplete (fed)
def helicsFederateRequestTimeIterativeAsync (fed, requestTime, iterate)
def helicsFederateRequestTimeIterativeComplete (fed, outIterate)
def helicsFederateGetName (fed, str, maxlen)
def helicsFederateSetTimeDelta (fed, time)
def helicsFederateSetOutputDelay (fed, outputDelay)
def helicsFederateSetInputDelay (fed, inputDelay)
def helicsFederateSetPeriod (fed, period, offset)
def helicsFederateSetFlag (fed, flag, flagValue)
def helicsFederateSetLoggingLevel (fed, loggingLevel)
def helicsFederateGetCurrentTime (fed)
def helicsCreateQuery (target, query)
def helicsQueryExecute (query, fed)
def helicsQueryExecuteAsync (query, fed)
def helicsQueryExecuteComplete (query)
def helicsQueryIsCompleted (query)
def helicsQueryFree (arg1)
def helicsFederateRegisterSubscription (fed, key, type, units)
def helicsFederateRegisterTypeSubscription (fed, key, type, units)
def helicsFederateRegisterOptionalSubscription (fed, key, type, units)
def helicsFederateRegisterOptionalTypeSubscription (fed, key, type, units)
def helicsFederateRegisterPublication (fed, key, type, units)
def helicsFederateRegisterTypePublication (fed, key, type, units)
def helicsFederateRegisterGlobalPublication (fed, key, type, units)
def helicsFederateRegisterGlobalTypePublication (fed, key, type, units)
def helicsPublicationPublish (pub, data, len)
def helicsPublicationPublishString (pub, str)
def helicsPublicationPublishInteger (pub, val)
def helicsPublicationPublishDouble (pub, val)
def helicsPublicationPublishComplex (pub, real, imag)
def helicsPublicationPublishVector (pub, data, len)
def helicsSubscriptionGetValueSize (sub)
def helicsSubscriptionGetValue (sub, data, maxlen, actualLength)
def helicsSubscriptionGetString (sub, str, maxlen)
def helicsSubscriptionGetInteger (sub, val)
def helicsSubscriptionGetDouble (sub)
def helicsSubscriptionGetComplex (sub)
def helicsSubscriptionGetVectorSize (sub)
def helicsSubscriptionGetVector (sub, data, maxlen, actualSize)
def helicsSubscriptionSetDefault (sub, data, len)
def helicsSubscriptionSetDefaultString (sub, str)
def helicsSubscriptionSetDefaultInteger (sub, val)
def helicsSubscriptionSetDefaultDouble (sub, val)
def helicsSubscriptionSetDefaultComplex (sub, real, imag)
def helicsSubscriptionSetDefaultVector (sub, len)
def helicsSubscriptionGetType (sub, str, maxlen)
def helicsPublicationGetType (pub, str, maxlen)
def helicsSubscriptionGetKey (sub, str, maxlen)
def helicsPublicationGetKey (pub, str, maxlen)
def helicsSubscriptionGetUnits (sub, str, maxlen)
def helicsPublicationGetUnits (pub, str, maxlen)
def helicsSubscriptionIsUpdated (sub)
def helicsSubscriptionLastUpdateTime (sub)
def helicsFederateRegisterEndpoint (fed, name, type)
def helicsFederateRegisterGlobalEndpoint (fed, name, type)
def helicsEndpointSetDefaultDestination (endpoint, dest)
def helicsEndpointSendMessageRaw (endpoint, dest, data, len)
def helicsEndpointSendEventRaw (endpoint, dest, data, len, time)
def helicsEndpointSendMessage (endpoint, message)
def helicsEndpointSubscribe (endpoint, key, type)
def helicsFederateHasMessage (fed)
def helicsEndpointHasMessage (endpoint)
def helicsFederateReceiveCount (fed)
def helicsEndpointReceiveCount (endpoint)
def helicsEndpointGetMessage (endpoint)
def helicsFederateGetMessage (fed)
def helicsEndpointGetType (endpoint, str, maxlen)
def helicsEndpointGetName (endpoint, str, maxlen)
def helicsFederateRegisterSourceFilter (fed, type, target, name)
def helicsFederateRegisterDestinationFilter (fed, type, target, name)
def helicsFederateRegisterCloningFilter (fed, deliveryEndpoint)
def helicsCoreRegisterSourceFilter (core, type, target, name)
def helicsCoreRegisterDestinationFilter (core, type, target, name)
def helicsCoreRegisterCloningFilter (fed, deliveryEndpoint)
def helicsFilterGetTarget (filt, str, maxlen)
def helicsFilterGetName (filt, str, maxlen)
def helicsFilterSet (filt, property, val)
def setString (filt, property, val)
def helicsFilterAddDestinationTarget (filt, dest)
def helicsFilterAddSourceTarget (filt, dest)
def helicsFilterAddDeliveryEndpoint (filt, dest)
def helicsFilterRemoveDestinationTarget (filt, dest)
def helicsFilterRemoveSourceTarget (filt, dest)
def helicsFilterRemoveDeliveryEndpoint (filt, dest)
Variables
constexpr identifier_type invalid_id_value = static_cast<identifier_type> (-1)
defining an invalid id value
constexpr interface_visibility GLOBAL = interface_visibility::global
constexpr interface_visibility LOCAL = interface_visibility::local
const ActionMessage::AdditionalInfo emptyAddInfo
constexpr auto LEADING_CHAR = '\xF3'
constexpr auto TAIL_CHAR1 = '\xFA'
constexpr auto TAIL_CHAR2 = '\xFC'
constexpr std::pair< action_message_def::action_t, const char * > actionStrings []
constexpr size_t actEnd = sizeof (actionStrings) / sizeof (actionPair)
constexpr int32_t cmd_info_basis = 65536
constexpr Core::federate_id_t invalid_fed_id = -2'000'000'000
constexpr Core::handle_id_t invalid_handle = -2'000'000'000
constexpr Core::handle_id_t direct_send_handle
this special handle can be used to directly send a message in a core
constexpr Core::federate_id_t global_federate_id_shift = 0x0001'0000
constexpr Core::federate_id_t global_broker_id_shift = 0x7000'0000
const std::vector< Core::handle_id_t > emptyHandles
constexpr Time startupTime = Time::minVal ()
constexpr Time initialTime {-1000000.0}
const std::map< std::string, timeUnits > timeUnitStrings
constexpr Time timeZero = Time::zeroVal ()
constexpr Time timeEpsilon = Time::epsilon ()
constexpr Time negEpsilon = -Time::epsilon ()
constexpr int versionMajor =HELICS_VERSION_MAJOR
constexpr int versionMinor =HELICS_VERSION_MINOR
constexpr int versionPatch =HELICS_VERSION_PATCH
def helics_ok = _helics.helics_ok
def helics_invalid_object = _helics.helics_invalid_object
def helics_invalid_argument = _helics.helics_invalid_argument
def helics_discard = _helics.helics_discard
def helics_terminated = _helics.helics_terminated
def helics_warning = _helics.helics_warning
def helics_invalid_state_transition = _helics.helics_invalid_state_transition
def helics_invalid_function_call = _helics.helics_invalid_function_call
def helics_error = _helics.helics_error
def helics_true = _helics.helics_true
def helics_false = _helics.helics_false
def no_iteration = _helics.no_iteration
def force_iteration = _helics.force_iteration
def iterate_if_needed = _helics.iterate_if_needed
def next_step = _helics.next_step
def iteration_error = _helics.iteration_error
def iteration_halted = _helics.iteration_halted
def iterating = _helics.iterating
def helics_startup_state = _helics.helics_startup_state
def helics_initialization_state = _helics.helics_initialization_state
def helics_execution_state = _helics.helics_execution_state
def helics_finalize_state = _helics.helics_finalize_state
def helics_error_state = _helics.helics_error_state
def helics_pending_init_state = _helics.helics_pending_init_state
def helics_pending_exec_state = _helics.helics_pending_exec_state
def helics_pending_time_state = _helics.helics_pending_time_state
def helics_pending_iterative_time_state = _helics.helics_pending_iterative_time_state
def helics_custom_filter = _helics.helics_custom_filter
def helics_delay_filter = _helics.helics_delay_filter
def helics_randomDelay_filter = _helics.helics_randomDelay_filter
def helics_randomDrop_filter = _helics.helics_randomDrop_filter
def helics_reroute_filter = _helics.helics_reroute_filter
def helics_clone_filter = _helics.helics_clone_filter
def data_t_swigregister = _helics.data_t_swigregister
def message_t_swigregister = _helics.message_t_swigregister
def helicsGetVersion = _helics.helicsGetVersion
def helicsIsCoreTypeAvailable = _helics.helicsIsCoreTypeAvailable
def helicsCreateCore = _helics.helicsCreateCore
def helicsCreateCoreFromArgs = _helics.helicsCreateCoreFromArgs
def helicsCreateBroker = _helics.helicsCreateBroker
def helicsCreateBrokerFromArgs = _helics.helicsCreateBrokerFromArgs
def helicsBrokerIsConnected = _helics.helicsBrokerIsConnected
def helicsCoreIsConnected = _helics.helicsCoreIsConnected
def helicsBrokerGetIdentifier = _helics.helicsBrokerGetIdentifier
def helicsCoreGetIdentifier = _helics.helicsCoreGetIdentifier
def helicsBrokerGetAddress = _helics.helicsBrokerGetAddress
def helicsCoreDisconnect = _helics.helicsCoreDisconnect
def helicsBrokerDisconnect = _helics.helicsBrokerDisconnect
def helicsCoreFree = _helics.helicsCoreFree
def helicsBrokerFree = _helics.helicsBrokerFree
def helicsCreateValueFederate = _helics.helicsCreateValueFederate
def helicsCreateValueFederateFromJson = _helics.helicsCreateValueFederateFromJson
def helicsCreateMessageFederate = _helics.helicsCreateMessageFederate
def helicsCreateMessageFederateFromJson = _helics.helicsCreateMessageFederateFromJson
def helicsCreateCombinationFederate = _helics.helicsCreateCombinationFederate
def helicsCreateCombinationFederateFromJson = _helics.helicsCreateCombinationFederateFromJson
def helicsFederateInfoCreate = _helics.helicsFederateInfoCreate
def helicsFederateInfoLoadFromArgs = _helics.helicsFederateInfoLoadFromArgs
def helicsFederateInfoFree = _helics.helicsFederateInfoFree
def helicsFederateInfoSetFederateName = _helics.helicsFederateInfoSetFederateName
def helicsFederateInfoSetCoreName = _helics.helicsFederateInfoSetCoreName
def helicsFederateInfoSetCoreInitString = _helics.helicsFederateInfoSetCoreInitString
def helicsFederateInfoSetCoreTypeFromString = _helics.helicsFederateInfoSetCoreTypeFromString
def helicsFederateInfoSetCoreType = _helics.helicsFederateInfoSetCoreType
def helicsFederateInfoSetFlag = _helics.helicsFederateInfoSetFlag
def helicsFederateInfoSetOutputDelay = _helics.helicsFederateInfoSetOutputDelay
def helicsFederateInfoSetTimeDelta = _helics.helicsFederateInfoSetTimeDelta
def helicsFederateInfoSetInputDelay = _helics.helicsFederateInfoSetInputDelay
def helicsFederateInfoSetTimeOffset = _helics.helicsFederateInfoSetTimeOffset
def helicsFederateInfoSetPeriod = _helics.helicsFederateInfoSetPeriod
def helicsFederateInfoSetMaxIterations = _helics.helicsFederateInfoSetMaxIterations
def helicsFederateInfoSetLoggingLevel = _helics.helicsFederateInfoSetLoggingLevel
def helicsFederateFinalize = _helics.helicsFederateFinalize
def helicsFederateFree = _helics.helicsFederateFree
def helicsCloseLibrary = _helics.helicsCloseLibrary
def helicsFederateEnterInitializationMode = _helics.helicsFederateEnterInitializationMode
def helicsFederateEnterInitializationModeAsync = _helics.helicsFederateEnterInitializationModeAsync
def helicsFederateIsAsyncOperationCompleted = _helics.helicsFederateIsAsyncOperationCompleted
def helicsFederateEnterInitializationModeComplete = _helics.helicsFederateEnterInitializationModeComplete
def helicsFederateEnterExecutionMode = _helics.helicsFederateEnterExecutionMode
def helicsFederateEnterExecutionModeAsync = _helics.helicsFederateEnterExecutionModeAsync
def helicsFederateEnterExecutionModeComplete = _helics.helicsFederateEnterExecutionModeComplete
def helicsFederateEnterExecutionModeIterative = _helics.helicsFederateEnterExecutionModeIterative
def helicsFederateEnterExecutionModeIterativeAsync = _helics.helicsFederateEnterExecutionModeIterativeAsync
def helicsFederateEnterExecutionModeIterativeComplete = _helics.helicsFederateEnterExecutionModeIterativeComplete
def helicsFederateGetState = _helics.helicsFederateGetState
def helicsFederateGetCoreObject = _helics.helicsFederateGetCoreObject
def helicsFederateRequestTime = _helics.helicsFederateRequestTime
def helicsFederateRequestTimeIterative = _helics.helicsFederateRequestTimeIterative
def helicsFederateRequestTimeAsync = _helics.helicsFederateRequestTimeAsync
def helicsFederateRequestTimeComplete = _helics.helicsFederateRequestTimeComplete
def helicsFederateRequestTimeIterativeAsync = _helics.helicsFederateRequestTimeIterativeAsync
def helicsFederateRequestTimeIterativeComplete = _helics.helicsFederateRequestTimeIterativeComplete
def helicsFederateGetName = _helics.helicsFederateGetName
def helicsFederateSetTimeDelta = _helics.helicsFederateSetTimeDelta
def helicsFederateSetOutputDelay = _helics.helicsFederateSetOutputDelay
def helicsFederateSetInputDelay = _helics.helicsFederateSetInputDelay
def helicsFederateSetPeriod = _helics.helicsFederateSetPeriod
def helicsFederateSetFlag = _helics.helicsFederateSetFlag
def helicsFederateSetLoggingLevel = _helics.helicsFederateSetLoggingLevel
def helicsFederateGetCurrentTime = _helics.helicsFederateGetCurrentTime
def helicsCreateQuery = _helics.helicsCreateQuery
def helicsQueryExecute = _helics.helicsQueryExecute
def helicsQueryExecuteAsync = _helics.helicsQueryExecuteAsync
def helicsQueryExecuteComplete = _helics.helicsQueryExecuteComplete
def helicsQueryIsCompleted = _helics.helicsQueryIsCompleted
def helicsQueryFree = _helics.helicsQueryFree
def HELICS_STRING_TYPE = _helics.HELICS_STRING_TYPE
def HELICS_DOUBLE_TYPE = _helics.HELICS_DOUBLE_TYPE
def HELICS_INT_TYPE = _helics.HELICS_INT_TYPE
def HELICS_COMPLEX_TYPE = _helics.HELICS_COMPLEX_TYPE
def HELICS_VECTOR_TYPE = _helics.HELICS_VECTOR_TYPE
def HELICS_RAW_TYPE = _helics.HELICS_RAW_TYPE
def helicsFederateRegisterSubscription = _helics.helicsFederateRegisterSubscription
def helicsFederateRegisterTypeSubscription = _helics.helicsFederateRegisterTypeSubscription
def helicsFederateRegisterOptionalSubscription = _helics.helicsFederateRegisterOptionalSubscription
def helicsFederateRegisterOptionalTypeSubscription = _helics.helicsFederateRegisterOptionalTypeSubscription
def helicsFederateRegisterPublication = _helics.helicsFederateRegisterPublication
def helicsFederateRegisterTypePublication = _helics.helicsFederateRegisterTypePublication
def helicsFederateRegisterGlobalPublication = _helics.helicsFederateRegisterGlobalPublication
def helicsFederateRegisterGlobalTypePublication = _helics.helicsFederateRegisterGlobalTypePublication
def helicsPublicationPublish = _helics.helicsPublicationPublish
def helicsPublicationPublishString = _helics.helicsPublicationPublishString
def helicsPublicationPublishInteger = _helics.helicsPublicationPublishInteger
def helicsPublicationPublishDouble = _helics.helicsPublicationPublishDouble
def helicsPublicationPublishComplex = _helics.helicsPublicationPublishComplex
def helicsPublicationPublishVector = _helics.helicsPublicationPublishVector
def helicsSubscriptionGetValueSize = _helics.helicsSubscriptionGetValueSize
def helicsSubscriptionGetValue = _helics.helicsSubscriptionGetValue
def helicsSubscriptionGetString = _helics.helicsSubscriptionGetString
def helicsSubscriptionGetInteger = _helics.helicsSubscriptionGetInteger
def helicsSubscriptionGetDouble = _helics.helicsSubscriptionGetDouble
def helicsSubscriptionGetComplex = _helics.helicsSubscriptionGetComplex
def helicsSubscriptionGetVectorSize = _helics.helicsSubscriptionGetVectorSize
def helicsSubscriptionGetVector = _helics.helicsSubscriptionGetVector
def helicsSubscriptionSetDefault = _helics.helicsSubscriptionSetDefault
def helicsSubscriptionSetDefaultString = _helics.helicsSubscriptionSetDefaultString
def helicsSubscriptionSetDefaultInteger = _helics.helicsSubscriptionSetDefaultInteger
def helicsSubscriptionSetDefaultDouble = _helics.helicsSubscriptionSetDefaultDouble
def helicsSubscriptionSetDefaultComplex = _helics.helicsSubscriptionSetDefaultComplex
def helicsSubscriptionSetDefaultVector = _helics.helicsSubscriptionSetDefaultVector
def helicsSubscriptionGetType = _helics.helicsSubscriptionGetType
def helicsPublicationGetType = _helics.helicsPublicationGetType
def helicsSubscriptionGetKey = _helics.helicsSubscriptionGetKey
def helicsPublicationGetKey = _helics.helicsPublicationGetKey
def helicsSubscriptionGetUnits = _helics.helicsSubscriptionGetUnits
def helicsPublicationGetUnits = _helics.helicsPublicationGetUnits
def helicsSubscriptionIsUpdated = _helics.helicsSubscriptionIsUpdated
def helicsSubscriptionLastUpdateTime = _helics.helicsSubscriptionLastUpdateTime
def helicsFederateRegisterEndpoint = _helics.helicsFederateRegisterEndpoint
def helicsFederateRegisterGlobalEndpoint = _helics.helicsFederateRegisterGlobalEndpoint
def helicsEndpointSetDefaultDestination = _helics.helicsEndpointSetDefaultDestination
def helicsEndpointSendMessageRaw = _helics.helicsEndpointSendMessageRaw
def helicsEndpointSendEventRaw = _helics.helicsEndpointSendEventRaw
def helicsEndpointSendMessage = _helics.helicsEndpointSendMessage
def helicsEndpointSubscribe = _helics.helicsEndpointSubscribe
def helicsFederateHasMessage = _helics.helicsFederateHasMessage
def helicsEndpointHasMessage = _helics.helicsEndpointHasMessage
def helicsFederateReceiveCount = _helics.helicsFederateReceiveCount
def helicsEndpointReceiveCount = _helics.helicsEndpointReceiveCount
def helicsEndpointGetMessage = _helics.helicsEndpointGetMessage
def helicsFederateGetMessage = _helics.helicsFederateGetMessage
def helicsEndpointGetType = _helics.helicsEndpointGetType
def helicsEndpointGetName = _helics.helicsEndpointGetName
def helicsFederateRegisterSourceFilter = _helics.helicsFederateRegisterSourceFilter
def helicsFederateRegisterDestinationFilter = _helics.helicsFederateRegisterDestinationFilter
def helicsFederateRegisterCloningFilter = _helics.helicsFederateRegisterCloningFilter
def helicsCoreRegisterSourceFilter = _helics.helicsCoreRegisterSourceFilter
def helicsCoreRegisterDestinationFilter = _helics.helicsCoreRegisterDestinationFilter
def helicsCoreRegisterCloningFilter = _helics.helicsCoreRegisterCloningFilter
def helicsFilterGetTarget = _helics.helicsFilterGetTarget
def helicsFilterGetName = _helics.helicsFilterGetName
def helicsFilterSet = _helics.helicsFilterSet
def setString = _helics.setString
def helicsFilterAddDestinationTarget = _helics.helicsFilterAddDestinationTarget
def helicsFilterAddSourceTarget = _helics.helicsFilterAddSourceTarget
def helicsFilterAddDeliveryEndpoint = _helics.helicsFilterAddDeliveryEndpoint
def helicsFilterRemoveDestinationTarget = _helics.helicsFilterRemoveDestinationTarget
def helicsFilterRemoveSourceTarget = _helics.helicsFilterRemoveSourceTarget
def helicsFilterRemoveDeliveryEndpoint = _helics.helicsFilterRemoveDeliveryEndpoint
Detailed Description
HELICS Application API
HELICS Core API
HELICS C++98 Interface
Typedef Documentation
defV
using helics::defV = typedef boost::variant<double, int64_t, std::string, std::complex<double>, std::vector<double>, std::vector<std::complex<double> >>
define a variant with the different types
Time
using helics::Time = typedef TimeRepresentation<count_time<9> >
Simulation virtual time.
Class represents time in the core.
Enumeration Type Documentation
action_message_flags
enum helics::action_message_flags : uint16_t
Enumerator
iterationRequested
indicator that an iteration has been requested
processingComplete
indicator that processing has been completed
pub_required
flag indicating a publication is required
filt_required
flag indicating that a filter requires a publication
error_flag
flag indicating an error condition associated with the command
indicator_flag
flag used for setting values
extra_flag1
extra flag
BasicHandleType
enum helics::BasicHandleType : char
define the type of the handle
Enumerator
HANDLE_PUB
handle to publish interface
HANDLE_SUB
handle to a subscribe interface
HANDLE_END
handle to an endpoint
HANDLE_SOURCE_FILTER
handle to a source filter
HANDLE_DEST_FILTER
handle to a destination filter
HANDLE_CLONE_FILTER
handle for a cloning filter
core_type
enum helics::core_type : int strong
the type of the cores that are available
Enumerator
DEFAULT
pick a core type depending on compile configuration usually either ZMQ if available or UDP
ZMQ
use the Zero MQ networking protocol
MPI
use MPI for operation on a parallel cluster
TEST
use the Test core if all federates are in the same process
INTERPROCESS
interprocess uses memory mapped files to transfer data (for use when all federates are on the same machine
IPC
same as INTERPROCESS
TCP
use a generic TCP protocol message stream to send messages
UDP
use UDP packets to send the data
UNRECOGNIZED
unknown
defined_filter_types
enum helics::defined_filter_types strong
a set of common defined filters
handle_check_mode
enum helics::handle_check_mode : char strong
defining some check modes for dealing with required or optional components
Enumerator
required
indicator that the publication or endpoint is required to be there
optional
indicator that the publication or endpoint is optional
helics_iteration_request
enum helics::helics_iteration_request : signed char strong
enumeration of the possible iteration requests by a federate
Enumerator
no_iterations
indicator that the iterations have completed
force_iteration
force an iteration whether it is needed or not
iterate_if_needed
indicator that the iterations need to continue
helics_type_t
enum helics::helics_type_t : int strong
the base types for helics
identifiers
enum helics::identifiers : char strong
the known types of identifiers
interface_visibility
enum helics::interface_visibility strong
enumeration of locality namespaces
iteration_result
enum helics::iteration_result : signed char strong
enumeration of the possible states of iteration
Enumerator
error
indicator that an error has occurred
next_step
indicator that the iterations have completed and the federate has moved to the next step
iterating
indicator that the iterations need to continue
halted
indicator that the simulation has been halted
iteration_state
enum helics::iteration_state : signed char strong
enumeration of the possible states of convergence
Enumerator
error
indicator that an error has occurred
continue_processing
the current loop should continue
next_step
indicator that the iterations have completed
iterating
indicator that the iterations need to continue
halted
indicator that the simulation has been halted
queue_state_t
enum helics::queue_state_t : int strong
enumeration of queue states
type_location
enum helics::type_location
enumeration of the order inside the variant so the Which function returns match the enumeration
vtype
enum helics::vtype : int strong
type code embedded in the objects so the library knows how to cast them appropriately
Function Documentation
actionMessageType()
const char * helics::actionMessageType (action_message_def::action_t action)
return the name of the action
Parameters
action The action to get the name for
Returns
a pointer to string with the name
Referenced by prettyPrintString().
argumentParser()
int helics::argumentParser (int argc, const char *const * argv, variable_map & vm_map, const ArgDescriptors & argDefinitions, const std::string & posName = std::string())
using boost argument_parser to process a set of command line arguments
Parameters
[in] argc the number of arguments
[in] argv the actual strings in the argument
[out] vm_map the variable_map of all the arguments
[in] argDefinitions the definition targets used for the processing
[in] posName,(optional) the name of a positional argument
Returns
helpReturn(-1) if the help argument was called and displayed, versionReturn(-2) if version argument was used 0 otherwise
Referenced by helics::TestBroker::displayHelp(), helics::NetworkBrokerData::displayHelp(), helics::CoreBroker::displayHelp(), helics::Echo::Echo(), helics::IpcCore::initializeFromArgs(), helics::TestBroker::initializeFromArgs(), helics::IpcBroker::initializeFromArgs(), helics::TestCore::initializeFromArgs(), helics::NetworkBrokerData::initializeFromArgs(), helics::CoreBroker::initializeFromArgs(), helics::BrokerBase::initializeFromCmdArgs(), helics::FederateInfo::loadInfoFromArgs(), helics::Player::Player(), helics::Recorder::Recorder(), and helics::Source::Source().
changeDetected()
bool helics::changeDetected (const defV & prevValue, const std::string & val, double deltaV)
detect a change from the previous values
Referenced by helics::Publication::publish().
checkActionFlag()
template<class FlagContainer , class FlagIndex > bool helics::checkActionFlag (const FlagContainer & M, FlagIndex flag) inline
template function to check a flag in an object containing a flags field
Referenced by prettyPrintString(), and helics::DependencyInfo::ProcessMessage().
cleanupHelicsLibrary()
helics::cleanupHelicsLibrary ()
function to do some housekeeping work
this runs some cleanup routines and tries to close out any residual thread that haven't been shutdown yet
References helics::BrokerFactory::cleanUpBrokers(), and helics::CoreFactory::cleanUpCores().
clearActionFlag()
template<class FlagContainer , class FlagIndex > void helics::clearActionFlag (FlagContainer & M, FlagIndex flag) inline
template function to clear a flag in an object containing a flags field
coreTypeFromString()
core_type helics::coreTypeFromString (std::string type)
generate a core type value from a std::string
Parameters
a string describing the desired core type
Returns
a value of the helics_core_type enumeration
Exceptions
invalid_argument if the string is not recognized
References DEFAULT, INTERPROCESS, MPI, TCP, TEST, UDP, UNRECOGNIZED, and ZMQ.
Referenced by helicsCreateBroker(), helicsCreateBrokerFromArgs(), helicsCreateCore(), helicsCreateCoreFromArgs(), helicsFederateInfoSetCoreTypeFromString(), loadFederateInfo(), and helics::FederateInfo::loadInfoFromArgs().
createMessageFromCommand() [1/2]
std::unique_ptr< Message > helics::createMessageFromCommand (const ActionMessage & cmd)
create a new message object that copies all the information from the ActionMessage into newly allocated memory for the message
References helics::ActionMessage::actionTime, helics::ActionMessage::info(), helics::ActionMessage::AdditionalInfo::orig_source, helics::ActionMessage::AdditionalInfo::original_dest, helics::ActionMessage::payload, helics::ActionMessage::AdditionalInfo::source, and helics::ActionMessage::AdditionalInfo::target.
Referenced by helics::CommonCore::deliverMessage(), and helics::CommonCore::processMessage().
createMessageFromCommand() [2/2]
std::unique_ptr< Message > helics::createMessageFromCommand (ActionMessage && cmd)
create a new message object that moves all the information from the ActionMessage into newly allocated memory for the message
extractInterfaceandPort()
std::pair< std::string, int > helics::extractInterfaceandPort (const std::string & address)
extract a port number and interface string from an address number
, if there is no port number it default to -1 this is true if none was listed or the interface doesn't use port numbers
Parameters
[in] address a string with an network location description i.e 127.0.0.1:34
Returns
a pair with a string and int with the interface name and port number
References extractInterfaceandPort().
Referenced by extractInterfaceandPort(), and helics::NetworkBrokerData::initializeFromArgs().
extractInterfaceandPortString()
std::pair< std::string, std::string > helics::extractInterfaceandPortString (const std::string & address)
extract a port number string and interface string from an address number
, if there is no port number it default to empty string this is true if none was listed or the interface doesn't use port numbers
Parameters
[in] address a string with an network location description i.e 127.0.0.1:34
Returns
a pair with 2 strings with the interface name and port number
References extractInterfaceandPortString().
Referenced by extractInterfaceandPortString().
filterTypeFromString()
defined_filter_types helics::filterTypeFromString (const std::string & filterType) noexcept
get the filter type from a string
getHelicsVersionString()
std::string helics::getHelicsVersionString ()
get a string with the helics version info
getLocalExternalAddressV4() [1/2]
std::string helics::getLocalExternalAddressV4 ()
get the external ipv4 address of the current computer
References getLocalExternalAddressV4().
Referenced by getLocalExternalAddressV4().
getLocalExternalAddressV4() [2/2]
std::string helics::getLocalExternalAddressV4 (const std::string & server)
get the external ipv4 Ethernet address of the current computer that best matches the listed server
References getLocalExternalAddressV4().
getTypeFromString()
helics_type_t helics::getTypeFromString (const std::string & typeName)
convert a string to a type
Referenced by helicsFederateRegisterGlobalPublication(), helicsFederateRegisterOptionalSubscription(), helicsFederateRegisterPublication(), and helicsFederateRegisterSubscription().
getValue() [1/4]
template<class X > X helics::getValue (std::shared_ptr< ValueFederate > & fed, const std::string & Key)
get a value directly from the subscription key name
this is a convenience function to get a value directly from the subscription key name this function should not be used as the primary means of retrieving value as it does involve an additional map find operation vs the member getValue calls
Parameters
fed a shared pointer to a valueFederate
key the name of the publication
getValue() [2/4]
template<class X > void helics::getValue (std::shared_ptr< ValueFederate > & fed, const std::string & Key, X & obj)
get a value directly from the subscription key name
this is a convenience function to get a value directly from the subscription key name this function should not be used as the primary means of retrieving value as it does involve an additional map find operation vs the member getValue calls
Parameters
fed a shared pointer to a valueFederate
key the name of the publication
obj the obj to store the retrieved value
getValue() [3/4]
template<class X > X helics::getValue (ValueFederate & fed, const std::string & Key)
get a value directly from the subscription key name
this is a convenience function to get a value directly from the subscription key name this function should not be used as the primary means of retrieving value as it does involve an additional map find operation vs the member getValue calls
Parameters
fed a reference to a valueFederate
key the name of the publication
References helics::ValueFederate::getSubscriptionId(), and helics::ValueFederate::getValue().
getValue() [4/4]
template<class X > void helics::getValue (ValueFederate & fed, const std::string & Key, X & obj)
get a value directly from the subscription key name
this is a convenience function to get a value directly from the subscription key name this function should not be used as the primary means of retrieving value as it does involve an additional map find operation vs the member getValue calls
Parameters
fed a reference to a valueFederate
key the name of the publication
obj the obj to store the retrieved value
References helics::ValueFederate::getSubscriptionId(), and helics::ValueFederate::getValue().
hasInfo()
bool helics::hasInfo (action_message_def::action_t action) inline
check if the action has an info structure associated with it
Referenced by helics::ActionMessage::ActionMessage(), and helics::ActionMessage::setAction().
helicsCloseLibrary()
def helics.helicsCloseLibrary ()
call when done using the helics library, this function will ensure the threads are closed properly if possible this should be the last call before exiting,
References helics::BrokerFactory.cleanUpBrokers(), helics::CoreFactory.cleanUpCores(), helics::LoggerManager.closeLogger(), and zmqContextManager.setContextToLeakOnDelete().
helicsFederateInfoCreate()
def helics.helicsFederateInfoCreate ()
create a federate info object for specifying federate information when constructing a federate
Returns
a helics_federate_info_t object which is a reference to the created object
helicsGetComplex()
std::complex< double > helics::helicsGetComplex (const std::string & val)
convert a string to a complex number
helicsGetComplexVector()
std::vector< std::complex< double > > helics::helicsGetComplexVector (const std::string & val)
convert a string to a complex vector
helicsGetVector()
std::vector< double > helics::helicsGetVector (const std::string & val)
convert a string to a vector
helicsGetVersion()
def helics.helicsGetVersion ()
get a version string for HELICS
helicsType()
template<class X > constexpr helics_type_t helics::helicsType ()
template class for generating a known name of a type
helicsTypeString()
std::string helics::helicsTypeString (core_type type)
generate a string based on the core type
References INTERPROCESS, IPC, MPI, TCP, TEST, UDP, and ZMQ.
invalidValue()
template<class X > X helics::invalidValue ()
generate an invalid value for the various types
isBlockSizeValid()
bool helics::isBlockSizeValid (int size, const publication_info & pubI) inline
function to check if the size is valid for the given type
References isBlockSizeValid(), and helics::publication_info::size.
Referenced by isBlockSizeValid(), and helics::ValueFederateManager::publish().
isCoreTypeAvailable()
bool helics::isCoreTypeAvailable (core_type type) noexcept
Returns true if core/broker type specified is available in current compilation.
References DEFAULT, INTERPROCESS, IPC, MPI, TCP, TEST, UDP, and ZMQ.
isDisconnectCommand()
bool helics::isDisconnectCommand (const ActionMessage & command) inline noexcept
check if a command is a disconnect command
isPriorityCommand()
bool helics::isPriorityCommand (const ActionMessage & command) inline noexcept
check if a command is a priority command
Referenced by helics::BrokerBase::addActionMessage(), and helics::CommsInterface::transmit().
isProtocolCommand()
bool helics::isProtocolCommand (const ActionMessage & command) inline noexcept
check if a command is a protocol command
isValidCommand()
bool helics::isValidCommand (const ActionMessage & command) inline noexcept
check if a command is a valid command
isValidIndex()
template<class sizeType , class SizedDataType > bool helics::isValidIndex (sizeType testSize, const SizedDataType & vec) inline
helper template to check whether an index is actually valid for a particular vector
Template Parameters
SizedDataType a vector like data type that must have a size function
Parameters
testSize an index to test
vec a reference to a vector like object that has a size method
Returns
true if it is a valid index false otherwise
Referenced by helics::CommonCore::getFederate(), helics::Federate::getFilterObject(), helics::CommonCore::getHandleFederate(), helics::CommonCore::getHandleInfo(), helics::Recorder::getMessage(), and helics::Recorder::getValue().
loadFederateInfo()
FederateInfo helics::loadFederateInfo (const std::string & jsonString)
generate a FederateInfo object from a json file
References helics::FederateInfo::coreInitString, helics::FederateInfo::coreName, helics::FederateInfo::coreType, coreTypeFromString(), helics::FederateInfo::forwardCompute, helics::CoreFederateInfo::inputDelay, loadJsonString(), loadJsonTime(), helics::CoreFederateInfo::maxIterations, helics::FederateInfo::name, helics::CoreFederateInfo::observer, helics::CoreFederateInfo::offset, helics::CoreFederateInfo::only_transmit_on_change, helics::CoreFederateInfo::only_update_on_change, helics::CoreFederateInfo::outputDelay, helics::CoreFederateInfo::period, helics::FederateInfo::rollback, helics::CoreFederateInfo::source_only, and helics::CoreFederateInfo::uninterruptible.
make_destination_filter() [1/2]
std::unique_ptr< DestinationFilter > helics::make_destination_filter (defined_filter_types type, Federate * fed, const std::string & target, const std::string & name = EMPTY_STRING)
create a destination filter
Parameters
type the type of filter to create
fed the federate to create the filter through
target the target endpoint all message with the specified target as a destination will route through the filter
name the name of the filter (optional)
Returns
a unique pointer to a destination Filter object, note destroying the object does not deactivate the filter
make_destination_filter() [2/2]
std::unique_ptr< DestinationFilter > helics::make_destination_filter (defined_filter_types type, Core * cr, const std::string & target, const std::string & name = EMPTY_STRING)
create a destination filter
Parameters
type the type of filter to create
cr the core to create the federate through
target the target endpoint all message with the specified target as a destination will route through the filter
name the name of the filter (optional)
Returns
a unique pointer to a destination Filter object, note destroying the object does not deactivate the filter
make_source_filter() [1/2]
std::unique_ptr< SourceFilter > helics::make_source_filter (defined_filter_types type, Core * cr, const std::string & target, const std::string & name = EMPTY_STRING)
create a source filter
Parameters
type the type of filter to create
cr the core to create the filter through
target the target endpoint all message coming from the specified source will route through the filter
name the name of the filter (optional)
Returns
a unique pointer to a source Filter object, note destroying the object does not deactivate the filter
make_source_filter() [2/2]
std::unique_ptr< SourceFilter > helics::make_source_filter (defined_filter_types type, Federate * fed, const std::string & target, const std::string & name = EMPTY_STRING)
create a source filter
Parameters
type the type of filter to create
fed the federate to create the filter through
target the target endpoint all message coming from the specified source will route through the filter
name the name of the filter (optional)
Returns
a unique pointer to a source Filter object, note destroying the object does not deactivate the filter
makePortAddress()
std::string helics::makePortAddress (const std::string & networkInterface, int portNumber)
generate a string with a full address based on an interface string and port number
, how things get merged depend on what interface is used some use port number some do not
Parameters
[in] interface a string with an interface description i.e 127.0.0.1
portNumber the number of the port to use
Returns
a string with the merged address
References makePortAddress().
Referenced by helics::UdpCore::getAddress(), helics::TcpCore::getAddress(), helics::UdpBroker::getAddress(), helics::ZmqCore::getAddress(), helics::ZmqBroker::getAddress(), helics::TcpBroker::getAddress(), and makePortAddress().
operator<<()
std::ostream & helics::operator<< (std::ostream & os, const ActionMessage & command)
stream operator for a command
References prettyPrintString().
prettyPrintString()
std::string helics::prettyPrintString (const ActionMessage & command)
generate a human readable string with information about a command
Parameters
command the command to generate the string for
Returns
a string representing information about the command
References actionMessageType(), checkActionFlag(), and error_flag.
Referenced by operator<<().
publish() [1/2]
template<class... Us> void helics::publish (std::shared_ptr< ValueFederate > & fed, const std::string & pubKey, Us... pargs)
publish directly from the publication key name
this is a convenience function to publish directly from the publication key
Parameters
fed a shared_ptr to a value federate
pubKey the name of the publication
Template Parameters
pargs any combination of arguments that go into the other publish commands
publish() [2/2]
template<class... Us> void helics::publish (ValueFederate & fed, const std::string & pubKey, Us... pargs)
publish directly from the publication key name
this is a convenience function to publish directly from the publication key this function should not be used as the primary means of publications as it does involve an additional map find operation vs the member publish calls
Parameters
fed a reference to a valueFederate
pubKey the name of the publication
Template Parameters
pargs any combination of arguments that go into the other publish commands
References helics::ValueFederate::getPublicationId(), and helics::ValueFederate::publish().
setActionFlag()
template<class FlagContainer , class FlagIndex > void helics::setActionFlag (FlagContainer & M, FlagIndex flag) inline
template function to set a flag in an object containing a flags field
Referenced by helics::TimeCoordinator::checkTimeGrant(), helics::TimeCoordinator::enteringExecMode(), helics::CommonCore::setFlag(), and helics::TimeCoordinator::timeRequest().
stringTranslateToCppName()
std::string helics::stringTranslateToCppName (std::string in) inline
translate a string to a C++ qualified name for variable naming purposes
timeUnitsFromString()
timeUnits helics::timeUnitsFromString (const std::string & unitString)
generate a time related unit,
Returns
a timeUnits enumeration value
Exceptions
Referenced by loadJsonTime().
typeNameString()
template<class X > std::string helics::typeNameString () inline
template class for generating a known name of a type
typeNameString< char >()
template<> std::string helics::typeNameString< char > () inline
for character
typeNameString< double >()
template<> std::string helics::typeNameString< double > () inline
for float
typeNameString< float >()
template<> std::string helics::typeNameString< float > () inline
for float
typeNameString< int64_t >()
template<> std::string helics::typeNameString< int64_t > () inline
for 64 bit unsigned integer
typeNameString< std::complex< double > >()
template<> std::string helics::typeNameString< std::complex< double > > () inline
for complex double
typeNameString< std::complex< float > >()
template<> std::string helics::typeNameString< std::complex< float > > () inline
for complex double
typeNameString< std::int32_t >()
template<> std::string helics::typeNameString< std::int32_t > () inline
for integer
typeNameString< std::uint32_t >()
template<> std::string helics::typeNameString< std::uint32_t > () inline
for unsigned integer
typeNameString< std::uint64_t >()
template<> std::string helics::typeNameString< std::uint64_t > () inline
for 64 bit unsigned integer
typeNameString< unsigned char >()
template<> std::string helics::typeNameString< unsigned char > () inline
for unsigned character
typeNameStringRef()
const std::string & helics::typeNameStringRef (helics_type_t type)
sometime we just need a ref to a string for the basic types
valueExtract() [1/2]
template<class X > std::enable_if_t<std::is_arithmetic<X>::value> helics::valueExtract (const defV & dv, X & val)
for numeric types
valueExtract() [2/2]
template<class X > std::enable_if_t<std::is_arithmetic<X>::value> helics::valueExtract (const data_view & dv, helics_type_t baseType, X & val)
assume it is some numeric type (int or double)
versionString()
std::string helics::versionString ()
Returns
a string containing version information
Referenced by helics::Echo::Echo(), helics::FederateInfo::loadInfoFromArgs(), helics::Player::Player(), helics::Recorder::Recorder(), and helics::Source::Source().
Variable Documentation
direct_send_handle
constexpr Core::handle_id_t helics::direct_send_handle
Initial value:
=
  -1'745'234
this special handle can be used to directly send a message in a core
Referenced by helics::CommonCore::sendMessage().
global_broker_id_shift
constexpr Core::federate_id_t helics::global_broker_id_shift = 0x7000'0000
a shift in the global id index to discriminate between global ids of brokers vs federates
global_federate_id_shift
constexpr Core::federate_id_t helics::global_federate_id_shift = 0x0001'0000
a shift in the global federate id numbers to allow discrimination between local ids and global ones this value allows 65535 federates to be available in each core 1,878,982,656 allowable federates in the system and 268,435,455 brokers allowed if we need more than that this program has been phenomenally successful beyond all wildest imaginations and we can probably afford to change these to 64 bit numbers to accommodate
timeUnitStrings
const std::map<std::string, timeUnits> helics::timeUnitStrings
Initial value:
{{"ps", timeUnits::ps},
                                                       {"ns", timeUnits::ns},
                                                       {"us", timeUnits::us},
                                                       {"ms", timeUnits::ms},
                                                       {"s", timeUnits::s},
                                                       {"sec", timeUnits::sec},
                                                       { "", timeUnits::sec },
                                                       {"seconds", timeUnits::sec},
                                                       {"second", timeUnits::sec},
                                                       {"min", timeUnits::minutes},
                                                       {"minute", timeUnits::minutes},
                                                       {"minutes", timeUnits::minutes},
                                                       {"hr", timeUnits::hr},
                                                       {"hour", timeUnits::hr},
                                                       {"hours", timeUnits::hr},
                                                       {"day", timeUnits::day},
                                                       {"week", timeUnits::week},
                                                       {"wk", timeUnits::week}}
versionMajor
constexpr int helics::versionMajor =HELICS_VERSION_MAJOR
get the Major version number
versionMinor
constexpr int helics::versionMinor =HELICS_VERSION_MINOR
get the Minor version number
versionPatch
constexpr int helics::versionPatch =HELICS_VERSION_PATCH
get the patch number